<?php

namespace App\Docs\Content;

class Part4
{
    public static function pages(): array
    {
        return [
            'finance' => [
                'title' => 'Keuangan & Akuntansi',
                'pages' => [
                    'coa' => [
                        'title' => 'Bagan Akun (COA)',
                        'module' => 'Keuangan → COA',
                        'permission' => 'finance.view',
                        'nav' => 'Keuangan & Akuntansi → Bagan Akun',
                        'shot' => 'accounting/coa.png',
                        'purpose' => 'Daftar akun standar (Aset/Kewajiban/Ekuitas/Pendapatan/Beban) yang menjadi tujuan seluruh jurnal.',
                        'steps' => ['Buka Bagan Akun.', 'Klik Tambah.', 'Isi kode, nama, tipe, subtipe.', 'Simpan.'],
                        'fields' => ['Tipe/Subtipe' => 'Menentukan laporan & mapping (cth. CASH/BANK/AR/AP).', 'Dapat Diposting' => 'Akun header tidak bisa dijurnal langsung.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola akun.'],
                        'workflow' => 'COA → dipakai mapping & jurnal.',
                        'expected' => 'Akun tampil di form jurnal & mapping.',
                        'errors' => ['Kode duplikat' => 'Gunakan kode unik.'],
                        'tips' => ['Jangan ubah kode akun yang sudah dipakai jurnal.'],
                        'related' => [['Jurnal', '/docs/finance/journals']],
                        'keywords' => 'coa akun chart bagan',
                    ],
                    'journals' => [
                        'title' => 'Jurnal',
                        'module' => 'Keuangan → Jurnal',
                        'permission' => 'journal.view (posting: journal.post, unpost: journal.unpost)',
                        'nav' => 'Keuangan & Akuntansi → Jurnal',
                        'shot' => 'accounting/journals.png',
                        'purpose' => 'Jurnal double-entry manual maupun otomatis dari transaksi. Wajib balance; posted immutable (koreksi via reversal). Kolom Sumber link ke dokumen asal.',
                        'steps' => ['Klik Jurnal Manual.', 'Pilih perusahaan, tanggal, keterangan.', 'Tambah minimal 2 baris (akun + debit/kredit).', 'Posting Jurnal (sistem menolak bila tidak balance).', 'Untuk koreksi: buka jurnal posted → Reverse (jurnal cermin).'],
                        'fields' => ['Debit/Kredit' => 'Total harus sama persis.', 'Sumber' => 'Link ke faktur/tagihan/WO/payroll/dll.'],
                        'buttons' => ['Posting Jurnal' => 'Kunci jurnal.', 'Reverse Jurnal' => 'Buat jurnal cermin (wajib alasan).', 'Detail' => 'Rincian baris + total.'],
                        'workflow' => 'DRAFT → POSTED → (REVERSAL bila koreksi).',
                        'expected' => 'Jurnal balance tercatat di semua laporan.',
                        'errors' => ['Tidak balance' => 'Samakan total debit & kredit.', 'Periode ditutup' => 'Posting ke periode terbuka.'],
                        'tips' => ['Klik nomor di kolom Sumber untuk melompat ke dokumen asal.'],
                        'related' => [['Neraca Saldo', '/docs/finance/trial-balance'], ['Buku Besar', '/docs/finance/ledger']],
                        'keywords' => 'jurnal journal debit kredit balance reversal manual',
                    ],
                    'trial-balance' => [
                        'title' => 'Neraca Saldo',
                        'module' => 'Keuangan → Neraca Saldo',
                        'permission' => 'ledger.view',
                        'nav' => 'Keuangan & Akuntansi → Neraca Saldo',
                        'shot' => 'accounting/trial-balance.png',
                        'purpose' => 'Total debit & kredit per akun per periode dengan indikator BALANCE.',
                        'steps' => ['Buka Neraca Saldo.', 'Atur periode.', 'Klik Filter.', 'Cetak bila perlu.'],
                        'fields' => [],
                        'buttons' => ['Filter' => 'Terapkan periode.', 'Cetak / PDF' => 'Cetak laporan.'],
                        'workflow' => 'Agregat jurnal POSTED.',
                        'expected' => 'Total debit = total kredit (✓ BALANCE).',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Buku Besar', '/docs/finance/ledger'], ['Laba Rugi', '/docs/finance/pl']],
                        'keywords' => 'neraca saldo trial balance',
                    ],
                    'ledger' => [
                        'title' => 'Buku Besar',
                        'module' => 'Keuangan → Buku Besar',
                        'permission' => 'ledger.view',
                        'nav' => 'Keuangan & Akuntansi → Buku Besar',
                        'shot' => 'accounting/ledger.png',
                        'purpose' => 'Rincian mutasi per akun dengan saldo berjalan.',
                        'steps' => ['Buka Buku Besar.', 'Pilih akun + periode.', 'Klik Filter.'],
                        'fields' => ['Saldo' => 'Berjalan per baris.'],
                        'buttons' => ['Filter' => 'Terapkan.', 'Cetak / PDF' => 'Cetak.'],
                        'workflow' => 'Dari jurnal POSTED akun terpilih.',
                        'expected' => 'Mutasi lengkap berurutan tanggal.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Neraca Saldo', '/docs/finance/trial-balance']],
                        'keywords' => 'buku besar ledger general mutasi',
                    ],
                    'pl' => [
                        'title' => 'Laba Rugi',
                        'module' => 'Keuangan → Laba Rugi',
                        'permission' => 'ledger.view',
                        'nav' => 'Keuangan & Akuntansi → Laba Rugi',
                        'shot' => 'accounting/pl.png',
                        'purpose' => 'Pendapatan − beban per periode = laba/rugi bersih.',
                        'steps' => ['Buka Laba Rugi.', 'Atur periode.', 'Klik Filter / Cetak.'],
                        'fields' => [],
                        'buttons' => ['Filter' => 'Terapkan.', 'Cetak / PDF' => 'Cetak.'],
                        'workflow' => 'Agregat akun REVENUE − EXPENSE.',
                        'expected' => 'Laba bersih periode.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Neraca', '/docs/finance/balance-sheet']],
                        'keywords' => 'laba rugi profit loss pl',
                    ],
                    'balance-sheet' => [
                        'title' => 'Neraca',
                        'module' => 'Keuangan → Neraca',
                        'permission' => 'ledger.view',
                        'nav' => 'Keuangan & Akuntansi → Neraca',
                        'shot' => 'accounting/balance-sheet.png',
                        'purpose' => 'Posisi aset = kewajiban + ekuitas (+ laba berjalan) per tanggal.',
                        'steps' => ['Buka Neraca.', 'Atur tanggal per.', 'Klik Filter / Cetak.'],
                        'fields' => [],
                        'buttons' => ['Filter' => 'Terapkan.', 'Cetak / PDF' => 'Cetak.'],
                        'workflow' => 'Agregat akun ASSET/LIABILITY/EQUITY + laba tahun berjalan.',
                        'expected' => 'Balance (selisih Rp 0).',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Laba Rugi', '/docs/finance/pl']],
                        'keywords' => 'neraca balance sheet aset kewajiban ekuitas',
                    ],
                    'cash-flow' => [
                        'title' => 'Arus Kas',
                        'module' => 'Keuangan → Arus Kas',
                        'permission' => 'ledger.view',
                        'nav' => 'Keuangan & Akuntansi → Arus Kas',
                        'shot' => 'accounting/cash-flow.png',
                        'purpose' => 'Mutasi kas & bank per sumber (pembayaran, deposit, gaji, supplier, CSR, modal) + saldo awal/akhir.',
                        'steps' => ['Buka Arus Kas.', 'Atur periode.', 'Klik Filter / Cetak.'],
                        'fields' => [],
                        'buttons' => ['Filter' => 'Terapkan.', 'Cetak / PDF' => 'Cetak.'],
                        'workflow' => 'Dari jurnal POSTED akun CASH/BANK.',
                        'expected' => 'Saldo akhir = awal + mutasi bersih.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Buku Besar', '/docs/finance/ledger']],
                        'keywords' => 'arus kas cash flow kas bank',
                    ],
                    'ar-aging' => [
                        'title' => 'Umur Piutang',
                        'module' => 'Keuangan → AR Aging',
                        'permission' => 'ledger.view',
                        'nav' => 'Keuangan & Akuntansi → Umur Piutang',
                        'shot' => 'accounting/ar-aging.png',
                        'purpose' => 'Outstanding piutang per bucket umur (belum jatuh tempo / 1–30 / 31–60 / 61–90 / >90 hari) untuk penagihan.',
                        'steps' => ['Buka Umur Piutang.', 'Tinjau bucket & daftar faktur.'],
                        'fields' => [],
                        'buttons' => [],
                        'workflow' => 'Dari faktur belum lunas.',
                        'expected' => 'Fokus tagih bucket tua dulu.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Faktur', '/docs/sales/invoices'], ['Umur Utang', '/docs/finance/ap-aging']],
                        'keywords' => 'piutang aging ar umur tagih',
                    ],
                    'ap-aging' => [
                        'title' => 'Umur Utang',
                        'module' => 'Keuangan → AP Aging',
                        'permission' => 'ledger.view',
                        'nav' => 'Keuangan & Akuntansi → Umur Utang',
                        'shot' => 'accounting/ap-aging.png',
                        'purpose' => 'Outstanding hutang supplier per bucket umur untuk perencanaan pembayaran.',
                        'steps' => ['Buka Umur Utang.', 'Tinjau bucket & daftar tagihan.'],
                        'fields' => [],
                        'buttons' => [],
                        'workflow' => 'Dari tagihan belum lunas.',
                        'expected' => 'Prioritas bayar yang jatuh tempo.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Tagihan Vendor', '/docs/procurement/vendor-bills']],
                        'keywords' => 'utang aging ap bayar supplier',
                    ],
                    'tax' => [
                        'title' => 'Pajak',
                        'module' => 'Keuangan → Pajak',
                        'permission' => 'tax.view',
                        'nav' => 'Keuangan & Akuntansi → Pajak',
                        'shot' => 'accounting/tax.png',
                        'purpose' => 'Kode pajak configurable (PPN 11/12%, PPN masukan, PBB, PPh 21) + transaksi pajak otomatis dari faktur & tagihan + rekap PPN keluaran−masukan.',
                        'steps' => ['Buka Pajak.', 'Tinjau kode & tarif.', 'Tinjau transaksi pajak per periode.', 'Catat manual PBB/SPT bila perlu.'],
                        'fields' => ['Tarif' => 'Di database, bukan hardcode — ikuti regulasi terkini.'],
                        'buttons' => [],
                        'workflow' => 'Faktur/vendor bill → tax transaction otomatis.',
                        'expected' => 'Rekap PPN siap lapor.',
                        'errors' => ['Tarif berubah' => 'Ubah kode pajak; hanya transaksi baru yang ikut.'],
                        'tips' => [],
                        'related' => [['Faktur', '/docs/sales/invoices']],
                        'keywords' => 'pajak ppn pbb pph spt tarif faktur',
                    ],
                ],
            ],
            'documents' => [
                'title' => 'Dokumen & CSR',
                'pages' => [
                    'documents' => [
                        'title' => 'Manajemen Dokumen',
                        'module' => 'Dokumen → Surat/Arsip',
                        'permission' => 'document.view (approve: document.approve)',
                        'nav' => 'Dokumen & CSR → Manajemen Dokumen',
                        'shot' => 'corporate/documents.png',
                        'purpose' => 'Surat masuk/keluar, internal, karyawan, vendor, legal, perizinan — dengan penomoran otomatis, lampiran, versi, kadaluarsa, dan download log.',
                        'steps' => ['Klik Tambah Dokumen.', 'Pilih kategori & divisi (untuk nomor surat).', 'Isi subjek, tanggal, kadaluarsa bila ada.', 'Upload lampiran (PDF/DOC/IMG ≤10MB).', 'Simpan (nomor otomatis: 001/DIVI/IX/2026).'],
                        'fields' => ['Nomor' => 'Otomatis per divisi per tahun.', 'Kadaluarsa' => 'Memicu pengingat & alert.'],
                        'buttons' => ['Simpan' => 'Arsipkan.', 'Setujui' => 'Approver mengesahkan.', 'Unduh' => 'Tercatat di download log.'],
                        'workflow' => 'DRAFT → SUBMITTED → APPROVED; ARCHIVED bila selesai.',
                        'expected' => 'Dokumen rapi, bernomor, terlacak.',
                        'errors' => ['File terlalu besar' => 'Maks 10MB; kompres dulu.'],
                        'tips' => ['Isi kadaluarsa untuk perizinan agar dapat reminder.'],
                        'related' => [['Program CSR', '/docs/documents/csr']],
                        'keywords' => 'dokumen surat arsip nomor lampiran legal permit',
                    ],
                    'csr' => [
                        'title' => 'Program CSR',
                        'module' => 'Dokumen → CSR',
                        'permission' => 'csr.view (approve: csr.approve)',
                        'nav' => 'Dokumen & CSR → Program CSR',
                        'shot' => 'corporate/csr.png',
                        'purpose' => 'Proposal → approval → aktivitas → beban (jurnal otomatis Dr CSR/Cr Kas) → dokumentasi & laporan.',
                        'steps' => ['Klik Proposal CSR Baru.', 'Isi nama, anggaran, periode.', 'Simpan → (approver) Setujui.', 'Tambah aktivitas & catat beban.', 'Upload dokumentasi.'],
                        'fields' => ['Anggaran vs Realisasi' => 'Dipantau di kartu program.'],
                        'buttons' => ['Simpan Proposal/Setujui' => 'Alur program.'],
                        'workflow' => 'PROPOSAL → APPROVED → IN_PROGRESS → COMPLETED.',
                        'expected' => 'Realisasi vs anggaran terpantau + jurnal beban.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Manajemen Dokumen', '/docs/documents/documents']],
                        'keywords' => 'csr sosial proposal anggaran beban',
                    ],
                ],
            ],
            'reports' => [
                'title' => 'Laporan',
                'pages' => [
                    'mining' => [
                        'title' => 'Laporan Produksi Tambang',
                        'module' => 'Laporan → Tambang',
                        'permission' => 'report.view',
                        'nav' => 'Laporan → Produksi Tambang',
                        'shot' => 'reports/mining.png',
                        'purpose' => 'Tonase per site/shift, produktivitas operator & peralatan (ton/jam).',
                        'steps' => ['Buka laporan.', 'Atur periode.', 'Filter/Cetak/Export CSV.'],
                        'fields' => [],
                        'buttons' => ['Filter' => 'Terapkan.', 'Cetak / PDF' => 'Cetak.', 'Export CSV' => 'Unduh CSV.'],
                        'workflow' => 'Dari aktivitas APPROVED/POSTED.',
                        'expected' => 'Tabel + total siap rapat.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Aktivitas Tambang', '/docs/mining/activity']],
                        'keywords' => 'laporan tambang tonase produktivitas',
                    ],
                    'inventory' => [
                        'title' => 'Laporan Inventory',
                        'module' => 'Laporan → Inventory',
                        'permission' => 'report.view',
                        'nav' => 'Laporan → Inventory',
                        'shot' => 'reports/inventory.png',
                        'purpose' => 'Saldo, status kritis, dan nilai stok per gudang.',
                        'steps' => ['Buka laporan.', 'Tinjau tabel + panel kritis.', 'Cetak/Export.'],
                        'fields' => [],
                        'buttons' => ['Cetak / PDF' => 'Cetak.', 'Export CSV' => 'Unduh CSV.'],
                        'workflow' => 'Dari stock ledger.',
                        'expected' => 'Item kritis ter-flag merah.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Saldo Stok', '/docs/inventory/stock-balance']],
                        'keywords' => 'laporan inventory stok kritis nilai',
                    ],
                    'sales' => [
                        'title' => 'Laporan Penjualan',
                        'module' => 'Laporan → Penjualan',
                        'permission' => 'report.view',
                        'nav' => 'Laporan → Penjualan',
                        'shot' => 'reports/sales.png',
                        'purpose' => 'Penjualan per customer & volume per produk + outstanding.',
                        'steps' => ['Buka laporan.', 'Atur periode.', 'Cetak/Export.'],
                        'fields' => [],
                        'buttons' => ['Filter' => 'Terapkan.', 'Cetak / PDF' => 'Cetak.', 'Export CSV' => 'Unduh CSV.'],
                        'workflow' => 'Dari faktur POSTED/lunas.',
                        'expected' => 'Omzet & outstanding jelas.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Faktur', '/docs/sales/invoices']],
                        'keywords' => 'laporan penjualan omzet customer produk',
                    ],
                    'hr' => [
                        'title' => 'Laporan HR',
                        'module' => 'Laporan → HR',
                        'permission' => 'report.view',
                        'nav' => 'Laporan → HR',
                        'shot' => 'reports/hr.png',
                        'purpose' => 'Rekap absensi per karyawan + payroll per periode.',
                        'steps' => ['Buka laporan.', 'Pilih periode (YYYY-MM).'],
                        'fields' => [],
                        'buttons' => ['Cetak / PDF' => 'Cetak.'],
                        'workflow' => 'Dari absensi & payroll run.',
                        'expected' => 'Kehadiran & biaya gaji terpantau.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Payroll', '/docs/hr/payroll']],
                        'keywords' => 'laporan hr absensi payroll karyawan',
                    ],
                    'maintenance' => [
                        'title' => 'Laporan Pemeliharaan',
                        'module' => 'Laporan → Maintenance',
                        'permission' => 'report.view',
                        'nav' => 'Laporan → Pemeliharaan',
                        'shot' => 'reports/maintenance.png',
                        'purpose' => 'Biaya & downtime per alat + daftar WO periode.',
                        'steps' => ['Buka laporan.', 'Atur periode.', 'Cetak.'],
                        'fields' => [],
                        'buttons' => ['Filter' => 'Terapkan.', 'Cetak / PDF' => 'Cetak.'],
                        'workflow' => 'Dari WO & downtime.',
                        'expected' => 'Alat boros biaya/downtime teridentifikasi.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Work Order', '/docs/maintenance/work-orders']],
                        'keywords' => 'laporan maintenance downtime biaya wo',
                    ],
                ],
            ],
            'approval' => [
                'title' => 'Persetujuan',
                'pages' => [
                    'center' => [
                        'title' => 'Pusat Persetujuan',
                        'module' => 'Persetujuan',
                        'permission' => 'approval.view (aksi: approval.approve)',
                        'nav' => 'Ikon perisai (topbar) → Persetujuan',
                        'shot' => 'approval/center.png',
                        'purpose' => 'Satu tempat bertindak atas semua permintaan persetujuan (PR, payroll, WO, void timbang, dll) + riwayat.',
                        'steps' => ['Buka Pusat Persetujuan (badge = jumlah menunggu).', 'Periksa modul, nomor, nilai.', 'Klik Setujui — atau Tolak dengan alasan.', 'Transaksi otomatis berubah status.'],
                        'fields' => [],
                        'buttons' => ['Setujui' => 'Lanjut ke step/transaksi APPROVED.', 'Tolak' => 'Wajib alasan; transaksi REJECTED.'],
                        'workflow' => 'PENDING → APPROVED/REJECTED/RETURNED; delegasi didukung.',
                        'expected' => 'Tidak ada antrean tak bertuan (resolver progresif).',
                        'errors' => ['Bukan giliran Anda' => 'Tindakan ditolak sistem.'],
                        'tips' => ['Gunakan delegasi saat cuti agar alur tak macet.'],
                        'related' => [['Permintaan Pembelian', '/docs/procurement/purchase-requests'], ['Alur Mine to Cash', '/docs/workflows/mine-to-cash']],
                        'keywords' => 'approval persetujuan approve tolak delegasi pending',
                    ],
                ],
            ],
            'audit' => [
                'title' => 'Audit',
                'pages' => [
                    'log' => [
                        'title' => 'Audit Trail',
                        'module' => 'Administrasi → Audit Trail',
                        'permission' => 'audit.view',
                        'nav' => 'Administrasi → Audit Trail',
                        'shot' => 'administration/audit.png',
                        'purpose' => 'Lihat siapa mengubah apa, kapan, dari IP mana — termasuk override timbangan, void, dan reset password.',
                        'steps' => ['Buka Audit Trail.', 'Filter modul/aksi/periode.'],
                        'fields' => [],
                        'buttons' => ['Filter/Reset' => 'Saring data.'],
                        'workflow' => 'Otomatis per aksi; immutable.',
                        'expected' => 'Jejak lengkap & tidak bisa dihapus user biasa.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Audit Trail (Admin)', '/docs/administration/audit']],
                        'keywords' => 'audit log jejak',
                    ],
                ],
            ],
            'workflows' => [
                'title' => 'Alur End-to-End',
                'pages' => [
                    'mine-to-cash' => [
                        'title' => 'Mine to Cash',
                        'module' => 'Alur: Tambang → Keuangan',
                        'permission' => 'dashboard.view',
                        'nav' => 'Dokumentasi → Alur End-to-End → Mine to Cash',
                        'shot' => 'dashboard/dashboard.png',
                        'purpose' => 'Alur utama: tambang → timbang → produksi → inventory → jual → DO → timbang keluar → faktur → bayar → jurnal.',
                        'steps' => ['Catat Aktivitas Tambang → Approve → Posting (stok raw +).', 'Batch Crusher → Approve → Posting (FG +).', 'Buat SO → Approve.', 'Buat DO → Timbang keluar → Selesaikan (stok −).', 'Buat Faktur dari SO (jurnal AR/pendapatan/PPN).', 'Terima Pembayaran (faktur lunas).', 'Cek Trial Balance & Laba Rugi.'],
                        'fields' => [],
                        'buttons' => [],
                        'workflow' => 'Satu nomor SO menautkan DO, tiket, faktur, pembayaran, jurnal.',
                        'expected' => 'Stok, piutang, kas, pendapatan konsisten & balance.',
                        'errors' => ['Stok tidak cukup' => 'Pastikan produksi sudah diposting.', 'Faktur ganda' => 'Satu SO = satu faktur aktif.'],
                        'tips' => ['Gunakan kolom tautan (SO↔DO↔tiket↔faktur) untuk telusur cepat.'],
                        'related' => [['Aktivitas Tambang', '/docs/mining/activity'], ['Faktur', '/docs/sales/invoices']],
                        'keywords' => 'alur mine to cash end to end tambang kas',
                    ],
                    'procure-to-pay' => [
                        'title' => 'Procure to Pay',
                        'module' => 'Alur: Beli → Bayar',
                        'permission' => 'dashboard.view',
                        'nav' => 'Dokumentasi → Alur End-to-End → Procure to Pay',
                        'shot' => 'procurement/purchase-orders.png',
                        'purpose' => 'PR → approval nominal → PO → GRN (stok +) → tagihan (hutang) → bayar (kas −).',
                        'steps' => ['Buat PR → Ajukan → Approve (matriks nominal).', 'Buat PO dari PR → Approve.', 'GRN dari PO → Posting (stok +).', 'Buat Tagihan → Posting (jurnal AP).', 'Bayar (penuh/parsial).', 'Cek Umur Utang & Buku Besar.'],
                        'fields' => [],
                        'buttons' => [],
                        'workflow' => 'PR/PO tidak menyentuh stok; hanya GRN.',
                        'expected' => 'Stok +, hutang lalu lunas, jurnal balance.',
                        'errors' => ['Over-receipt/over-billing' => 'Ditolak sistem.'],
                        'tips' => [],
                        'related' => [['Permintaan Pembelian', '/docs/procurement/purchase-requests'], ['Tagihan Vendor', '/docs/procurement/vendor-bills']],
                        'keywords' => 'procure to pay pr po grn tagihan bayar',
                    ],
                    'payroll' => [
                        'title' => 'Payroll to Accounting',
                        'module' => 'Alur: HR → Jurnal',
                        'permission' => 'dashboard.view',
                        'nav' => 'Dokumentasi → Alur End-to-End → Payroll',
                        'shot' => 'hr/payroll.png',
                        'purpose' => 'Absensi → lembur → insentif (approved) → kalkulasi → approve → posting → bayar.',
                        'steps' => ['Pastikan absensi & lembur tercatat.', 'Approve insentif operator.', 'Buat run → Kalkulasi → periksa detail.', 'Setujui → Posting Jurnal → Bayar.', 'Cetak slip.'],
                        'fields' => [],
                        'buttons' => [],
                        'workflow' => 'Neto = bruto − potongan − PPh21.',
                        'expected' => 'Gaji + jurnal + slip konsisten.',
                        'errors' => ['Insentif tidak masuk' => 'Harus APPROVED sebelum kalkulasi.'],
                        'tips' => [],
                        'related' => [['Payroll', '/docs/hr/payroll'], ['Jurnal', '/docs/finance/journals']],
                        'keywords' => 'payroll gaji jurnal slip pph',
                    ],
                    'maintenance' => [
                        'title' => 'Alur Maintenance',
                        'module' => 'Alur: Aset → Selesai',
                        'permission' => 'dashboard.view',
                        'nav' => 'Dokumentasi → Alur End-to-End → Maintenance',
                        'shot' => 'maintenance/work-orders.png',
                        'purpose' => 'Aset → jadwal/WO → teknisi + sparepart → issue (stok −, biaya +, jurnal) → selesai + downtime.',
                        'steps' => ['Buat WO dari jadwal/kerusakan.', 'Setujui → Mulai.', 'Issue sparepart.', 'Selesaikan + isi downtime.', 'Tinjau laporan biaya/downtime.'],
                        'fields' => [],
                        'buttons' => [],
                        'workflow' => 'Issue = ledger OUT + cost + jurnal sekaligus.',
                        'expected' => 'Biaya & downtime per alat terpantau.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Work Order', '/docs/maintenance/work-orders']],
                        'keywords' => 'maintenance wo sparepart downtime',
                    ],
                ],
            ],
            'faq' => [
                'title' => 'FAQ',
                'pages' => [
                    'general' => [
                        'title' => 'Pertanyaan Umum',
                        'module' => 'Bantuan',
                        'permission' => '—',
                        'nav' => 'Dokumentasi → FAQ',
                        'shot' => 'dashboard/dashboard.png',
                        'purpose' => 'Jawaban cepat atas pertanyaan yang sering muncul.',
                        'steps' => [],
                        'fields' => [],
                        'buttons' => [],
                        'workflow' => '',
                        'expected' => '',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Troubleshooting', '/docs/troubleshooting/common'], ['Login', '/docs/getting-started/login']],
                        'keywords' => 'faq tanya jawab umum bantuan',
                        'faqs' => [
                            ['Bagaimana reset password user?', 'Administrasi → Manajemen Pengguna → Reset Password. User mendapat password sementara + wajib ganti saat login.'],
                            ['Mengapa menu saya sedikit?', 'Menu mengikuti izin peran. Minta admin menambah izin via Matriks Izin.'],
                            ['Mengapa tombol aksi 403?', 'Peran butuh izin aksi spesifik (approve/post/dll), bukan hanya view.'],
                            ['Stok tidak berkurang setelah DO?', 'DO harus diselesaikan dengan tiket timbangan (Selesaikan + Timbang).'],
                            ['Faktur tidak bisa dibuat dua kali?', 'Satu SO = satu faktur aktif (anti duplikat). Batalkan/void dulu bila salah.'],
                            ['Insentif tidak masuk payroll?', 'Insentif harus APPROVED sebelum kalkulasi periode itu.'],
                            ['Bagaimana alokasi deposit?', 'Centang gunakan deposit saat buat faktur; jurnal alokasi terbentuk otomatis.'],
                            ['Jurnal tidak balance?', 'Samakan total debit & kredit; sistem menolak posting timpang.'],
                        ],
                    ],
                ],
            ],
            'troubleshooting' => [
                'title' => 'Troubleshooting',
                'pages' => [
                    'common' => [
                        'title' => 'Masalah Umum & Solusi',
                        'module' => 'Bantuan',
                        'permission' => '—',
                        'nav' => 'Dokumentasi → Troubleshooting',
                        'shot' => 'dashboard/dashboard.png',
                        'purpose' => 'Panduan perbaikan mandiri untuk error operasional umum.',
                        'steps' => [],
                        'fields' => [],
                        'buttons' => [],
                        'workflow' => '',
                        'expected' => '',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['FAQ', '/docs/faq/general']],
                        'keywords' => 'troubleshoot error masalah solusi gagal',
                        'faqs' => [
                            ['Error "Stok tidak cukup"', 'Cek Saldo Stok & Kartu Stok; pastikan gudang benar; posting produksi/GRN dulu bila perlu.'],
                            ['Error "Jurnal tidak balance"', 'Samakan total debit & kredit sampai selisih Rp 0.'],
                            ['Error "Periode ditutup"', 'Posting ke periode OPEN atau minta Finance membuka periode.'],
                            ['Error "Melebihi sisa PO/SO"', 'Kurangi qty sesuai sisa; buat dokumen baru untuk sisanya.'],
                            ['Error "Akun terkunci (LOCKED)"', 'Minta admin Unlock; cek Login History untuk pola gagal.'],
                            ['Halaman 500 setelah update', 'Jalankan php artisan optimize:clear; cek storage/logs/laravel.log.'],
                            ['miningerp.test tampil daftar file', 'Pastikan DocumentRoot Apache ke folder public lalu restart Apache.'],
                            ['Screenshot docs kosong', 'Pastikan demo seed ada & user superadmin aktif; jalankan ulang php artisan docs:screenshot.'],
                        ],
                    ],
                ],
            ],
        ];
    }
}
