<?php

namespace App\Docs\Content;

class Part3
{
    public static function pages(): array
    {
        return [
            'sales' => [
                'title' => 'Penjualan',
                'pages' => [
                    'customers' => [
                        'title' => 'Customer',
                        'module' => 'Penjualan → Customer',
                        'permission' => 'sales.view',
                        'nav' => 'Penjualan → Customer',
                        'shot' => 'sales/customers.png',
                        'purpose' => 'Master pelanggan: identitas, termin, limit kredit, dan grup harga.',
                        'steps' => ['Buka Penjualan → Customer.', 'Klik Tambah.', 'Isi kode/nama/NPWP/alamat/kontak.', 'Pilih termin & limit kredit + grup.', 'Simpan.'],
                        'fields' => ['Termin' => 'Jatuh tempo faktur otomatis.', 'Limit Kredit' => 'Batas piutang.', 'Grup' => 'Acuan harga grup.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Customer dipakai SO, faktur, deposit, pembayaran.',
                        'expected' => 'Customer tampil di seluruh form penjualan.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Order Penjualan', '/docs/sales/sales-orders'], ['Deposit', '/docs/sales/deposits']],
                        'keywords' => 'customer pelanggan termin kredit grup',
                    ],
                    'sales-orders' => [
                        'title' => 'Order Penjualan (SO)',
                        'module' => 'Penjualan → SO',
                        'permission' => 'sales_order.view (approve: sales_order.approve)',
                        'nav' => 'Penjualan → Order Penjualan',
                        'shot' => 'sales/sales-orders.png',
                        'purpose' => 'Order jual dengan harga otomatis dari daftar harga berjenjang (customer → grup → site → standar) + PPN.',
                        'steps' => ['Klik Buat SO.', 'Pilih perusahaan & customer.', 'Tambah item + qty (harga auto bila kosong).', 'Simpan → Setujui.'],
                        'fields' => ['Harga' => 'Kosongkan untuk harga otomatis berjenjang.', 'Total' => 'Subtotal + PPN.'],
                        'buttons' => ['Simpan/Setujui' => 'Alur dokumen.', 'Faktur (kolom)' => 'Link ke faktur bila sudah ada.'],
                        'workflow' => 'DRAFT → APPROVED → PARTIALLY_DELIVERED → COMPLETED.',
                        'expected' => 'SO approved bisa dibuatkan surat jalan.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Surat Jalan', '/docs/sales/delivery-orders'], ['Daftar Harga', '/docs/sales/price-lists']],
                        'keywords' => 'so sales order harga otomatis ppn',
                    ],
                    'delivery-orders' => [
                        'title' => 'Surat Jalan (DO)',
                        'module' => 'Penjualan → DO',
                        'permission' => 'delivery_order.view',
                        'nav' => 'Penjualan → Surat Jalan',
                        'shot' => 'sales/delivery-orders.png',
                        'purpose' => 'Pengiriman barang: quantity rencana → timbang keluar → quantity final → stok keluar otomatis.',
                        'steps' => ['Klik Buat DO dari SO yang approved.', 'Pilih gudang, tanggal, nopol, supir.', 'Isi qty per item (≤ sisa SO).', 'Simpan.', 'Lakukan timbang keluar di modul Timbangan.', 'Klik Selesaikan + Timbang → masukkan nomor tiket.'],
                        'fields' => ['Qty Order vs Kirim' => 'Final mengikuti NET timbangan.', 'Tiket' => 'Terhubung & terposting.'],
                        'buttons' => ['Simpan' => 'DRAFT.', 'Selesaikan + Timbang' => 'Stok keluar + update SO (anti double-posting).'],
                        'workflow' => 'DRAFT → COMPLETED.',
                        'expected' => 'Stok berkurang sebesar NET; SO ter-update.',
                        'errors' => ['Qty melebihi sisa SO' => 'Ditolak (anti over-delivery).', 'Stok tidak cukup' => 'Ditolak (anti minus).', 'Tiket belum lengkap' => 'Selesaikan timbang kedua dulu.'],
                        'tips' => ['Kolom Tiket link langsung ke tiket timbangan.'],
                        'related' => [['Tiket Timbangan', '/docs/weighbridge/tickets'], ['Faktur', '/docs/sales/invoices']],
                        'keywords' => 'do surat jalan kirim timbang loading',
                    ],
                    'invoices' => [
                        'title' => 'Faktur Penjualan',
                        'module' => 'Penjualan → Faktur',
                        'permission' => 'invoice.view',
                        'nav' => 'Penjualan → Faktur',
                        'shot' => 'sales/invoices.png',
                        'purpose' => 'Faktur dari quantity terkirim SO: otomatis PPN + jurnal (Dr Piutang / Cr Pendapatan / Cr PPN) + opsional pelunasan deposit.',
                        'steps' => ['Klik Dari SO.', 'Pilih SO yang sudah terkirim.', 'Centang gunakan deposit bila perlu.', 'Buat & Posting Faktur.'],
                        'fields' => ['Subtotal/PPN/Total' => 'Dihitung dari qty terkirim.', 'Dibayar' => 'Terisi via deposit/pembayaran.'],
                        'buttons' => ['Buat & Posting Faktur' => 'Faktur + jurnal + pajak tercatat.', 'Detail' => 'Rincian + link SO.'],
                        'workflow' => 'POSTED → PARTIALLY_PAID → PAID. Satu SO = satu faktur aktif.',
                        'expected' => 'Piutang + pendapatan + PPN tercatat.',
                        'errors' => ['Belum ada pengiriman' => 'Selesaikan DO dulu.', 'SO sudah berfaktur' => 'Faktur ganda ditolak.'],
                        'tips' => ['Filter Jatuh tempo untuk penagihan.'],
                        'related' => [['Pembayaran', '/docs/sales/payments'], ['Umur Piutang', '/docs/finance/ar-aging']],
                        'keywords' => 'faktur invoice ppn piutang posting',
                    ],
                    'payments' => [
                        'title' => 'Penerimaan Pembayaran',
                        'module' => 'Penjualan → Pembayaran',
                        'permission' => 'payment.view (buat: payment.create)',
                        'nav' => 'Penjualan → Pembayaran',
                        'shot' => 'sales/payments.png',
                        'purpose' => 'Terima pembayaran customer dengan alokasi otomatis FIFO ke faktur outstanding + jurnal (Dr Kas / Cr Piutang).',
                        'steps' => ['Klik Tambah.', 'Pilih perusahaan, customer, tanggal, metode, kas/bank.', 'Isi jumlah.', 'Simpan.'],
                        'fields' => ['Metode' => 'Tunai/Transfer/Cek/Giro/VA.', 'Alokasi' => 'Otomatis ke faktur tertua.'],
                        'buttons' => ['Simpan' => 'Bayar + jurnal.'],
                        'workflow' => 'POSTED langsung (tunai).',
                        'expected' => 'Faktur menjadi lunas/parsial; kas bertambah.',
                        'errors' => ['Melebihi outstanding' => 'Ditolak; kelebihan harus jadi deposit/refund manual.'],
                        'tips' => [],
                        'related' => [['Faktur', '/docs/sales/invoices'], ['Deposit', '/docs/sales/deposits']],
                        'keywords' => 'pembayaran payment terima kas fifo alokasi',
                    ],
                    'deposits' => [
                        'title' => 'Deposit Customer',
                        'module' => 'Penjualan → Deposit',
                        'permission' => 'deposit.view (buat: deposit.create)',
                        'nav' => 'Penjualan → Deposit Customer',
                        'shot' => 'sales/deposits.png',
                        'purpose' => 'Uang muka customer berbasis ledger (IN/USED/REFUND): saldo dihitung, anti-overdraft, terintegrasi jurnal + faktur + statement.',
                        'steps' => ['Isi form Deposit Masuk (customer, jumlah, kas/bank) → Terima Deposit.', 'Untuk refund: isi form Refund → proses.', 'Lihat Statement per customer.', 'Saat buat faktur, centang gunakan deposit untuk alokasi otomatis (+ jurnal Dr Deposit/Cr Piutang).'],
                        'fields' => ['Saldo' => 'IN − USED − REFUND (dihitung).'],
                        'buttons' => ['Terima Deposit' => 'Jurnal Dr Kas/Cr Deposit.', 'Refund' => 'Jurnal balik + cek saldo.', 'Statement' => 'Ledger berjalan per customer.'],
                        'workflow' => 'DEPOSIT_IN → (USED saat faktur) / REFUND.',
                        'expected' => 'Saldo akurat; tidak bisa dipakai melebihi saldo.',
                        'errors' => ['Saldo tidak cukup' => 'Kurangi nominal atau terima deposit dulu.'],
                        'tips' => [],
                        'related' => [['Faktur', '/docs/sales/invoices']],
                        'keywords' => 'deposit uang muka refund statement alokasi ledger',
                    ],
                    'price-lists' => [
                        'title' => 'Daftar Harga',
                        'module' => 'Penjualan → Harga',
                        'permission' => 'price.view (approve: price.approve)',
                        'nav' => 'Penjualan → Daftar Harga',
                        'shot' => 'sales/price-lists.png',
                        'purpose' => 'Harga jual berjenjang: customer → grup → site → standar, dengan masa berlaku dan approval + riwayat.',
                        'steps' => ['Klik Buat.', 'Pilih tipe & scope (customer/site/umum).', 'Isi item + harga (+ min qty).', 'Tentukan efektif & kedaluwarsa.', 'Simpan → Setujui.'],
                        'fields' => ['Tipe' => 'STANDARD/CUSTOMER/SITE/CONTRACT/RETAIL/SPECIAL.', 'Efektif' => 'Hanya harga aktif yang dipakai.'],
                        'buttons' => ['Simpan/Setujui' => 'Alur + price history.'],
                        'workflow' => 'DRAFT → APPROVED (aktif).',
                        'expected' => 'SO otomatis memakai harga yang tepat.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Selisih Harga', '/docs/sales/price-variances'], ['Order Penjualan', '/docs/sales/sales-orders']],
                        'keywords' => 'harga price list customer kontrak efektif',
                    ],
                    'price-variances' => [
                        'title' => 'Selisih Harga',
                        'module' => 'Penjualan → Selisih Harga',
                        'permission' => 'price_variance.view (approve: price_variance.approve)',
                        'nav' => 'Penjualan → Selisih Harga',
                        'shot' => 'sales/price-variances.png',
                        'purpose' => 'Membandingkan harga referensi (ritel) vs realisasi faktur. Informatif: hijau favorable, merah unfavorable — makna akuntansi via konfigurasi, bukan otomatis laba/rugi.',
                        'steps' => ['Data terbentuk otomatis dari faktur (bila harga referensi diset).', 'Tinjau daftar.', 'Setujui untuk pengakuan sesuai konfigurasi.'],
                        'fields' => ['Variance' => '(Realisasi − Referensi) × qty.', '%' => 'Persentase selisih.'],
                        'buttons' => ['Setujui' => 'Sahkan perlakuan akuntansi.'],
                        'workflow' => 'PENDING → APPROVED.',
                        'expected' => 'Selisih terdokumentasi & disetujui.',
                        'errors' => [],
                        'tips' => ['Selisih ≥10% memicu alert otomatis.'],
                        'related' => [['Daftar Harga', '/docs/sales/price-lists']],
                        'keywords' => 'selisih variance referensi realisasi favorable',
                    ],
                ],
            ],
            'maintenance' => [
                'title' => 'Aset & Pemeliharaan',
                'pages' => [
                    'assets' => [
                        'title' => 'Aset',
                        'module' => 'Aset → Register',
                        'permission' => 'asset.view',
                        'nav' => 'Aset & Pemeliharaan → Aset',
                        'shot' => 'maintenance/assets.png',
                        'purpose' => 'Register aset: kode, serial, perolehan, lokasi, penanggung jawab, status lifecycle, penyusutan.',
                        'steps' => ['Buka Aset.', 'Klik Tambah.', 'Isi identitas, tanggal & harga perolehan, umur ekonomis.', 'Simpan.'],
                        'fields' => ['Status' => 'AVAILABLE/IN_USE/MAINTENANCE/BREAKDOWN/RETIRED/DISPOSED.', 'Umur Ekonomis' => 'Dasar penyusutan.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Aset dipakai WO & jadwal maintenance.',
                        'expected' => 'Aset tersedia untuk WO.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Work Order', '/docs/maintenance/work-orders'], ['Peralatan', '/docs/maintenance/equipment']],
                        'keywords' => 'aset asset register perolehan penyusutan',
                    ],
                    'equipment' => [
                        'title' => 'Peralatan',
                        'module' => 'Aset → Peralatan',
                        'permission' => 'asset.view',
                        'nav' => 'Aset & Pemeliharaan → Peralatan',
                        'shot' => 'maintenance/equipment.png',
                        'purpose' => 'Armada alat berat & kendaraan: excavator, loader, dump truck, crusher, dll — plus meter reading & status.',
                        'steps' => ['Buka Peralatan.', 'Klik Tambah.', 'Isi kode/nama/tipe/merek/model/nopol/kepemilikan.', 'Simpan.'],
                        'fields' => ['Kepemilikan' => 'Milik/Sewa.', 'Meter' => 'Jam/KM untuk jadwal berbasis running hour.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Dipakai aktivitas tambang, hauling, WO.',
                        'expected' => 'Alat tampil di form tambang & WO.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Aktivitas Tambang', '/docs/mining/activity']],
                        'keywords' => 'peralatan equipment excavator dump truck alat berat',
                    ],
                    'work-orders' => [
                        'title' => 'Work Order',
                        'module' => 'Pemeliharaan → WO',
                        'permission' => 'work_order.view (approve: work_order.approve)',
                        'nav' => 'Aset & Pemeliharaan → Work Order',
                        'shot' => 'maintenance/work-orders.png',
                        'purpose' => 'Perintah kerja perawatan: task, teknisi, sparepart → issue (stok keluar + biaya + jurnal) → selesai + downtime.',
                        'steps' => ['Klik Buat WO.', 'Pilih alat/aset, tipe, prioritas, deskripsi, estimasi.', 'Tambah task, sparepart (+ gudang), teknisi.', 'Simpan → Setujui → Mulai.', 'Issue sparepart per baris.', 'Selesaikan (isi downtime + biaya tenaga).'],
                        'fields' => ['Tipe' => 'PREVENTIVE/CORRECTIVE/BREAKDOWN.', 'Downtime' => 'Jam berhenti alat.'],
                        'buttons' => ['Simpan/Setujui/Mulai' => 'Alur WO.', 'Issue Sparepart' => 'Stok −, biaya +, jurnal Dr Maintenance/Cr Sparepart.', 'Selesaikan' => 'Tutup WO + update status alat.'],
                        'workflow' => 'DRAFT → APPROVED → IN_PROGRESS → COMPLETED.',
                        'expected' => 'Biaya & downtime tercatat akurat.',
                        'errors' => ['Stok sparepart kurang' => 'Tambah stok / ganti gudang.', 'Issue ganda' => 'Ditolak (sudah ISSUED).'],
                        'tips' => ['Klik nama alat untuk detail peralatan.'],
                        'related' => [['Jadwal Pemeliharaan', '/docs/maintenance/schedules'], ['Saldo Stok', '/docs/inventory/stock-balance']],
                        'keywords' => 'work order wo teknisi sparepart downtime issue',
                    ],
                    'schedules' => [
                        'title' => 'Jadwal Pemeliharaan',
                        'module' => 'Pemeliharaan → Jadwal',
                        'permission' => 'maintenance.view',
                        'nav' => 'Aset & Pemeliharaan → Jadwal Pemeliharaan',
                        'shot' => 'maintenance/schedules.png',
                        'purpose' => 'Jadwal preventive/corrective berbasis jam kerja, KM, hari, atau bulan — dengan pengingat jatuh tempo.',
                        'steps' => ['Klik Buat Jadwal.', 'Pilih alat, tipe, basis interval, nilai.', 'Isi terakhir dilakukan.', 'Simpan.'],
                        'fields' => ['Interval' => 'RUNNING_HOUR/KM/DAY/MONTH + nilai.', 'Jatuh Tempo' => 'Merah bila lewat; memicu alert.'],
                        'buttons' => ['Simpan' => 'Buat jadwal.'],
                        'workflow' => 'Jadwal → WO saat jatuh tempo.',
                        'expected' => 'Perawatan terjadwal terpantau.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Work Order', '/docs/maintenance/work-orders']],
                        'keywords' => 'jadwal schedule preventive interval jatuh tempo',
                    ],
                ],
            ],
        ];
    }
}
