<?php

namespace App\Docs\Content;

class Part2
{
    public static function pages(): array
    {
        return [
            'mining' => [
                'title' => 'Operasi Tambang',
                'pages' => [
                    'activity' => [
                        'title' => 'Aktivitas Tambang',
                        'module' => 'Operasi Tambang → Aktivitas',
                        'permission' => 'mining.view (approve: mining.approve, post: mining.post)',
                        'nav' => 'Operasi Tambang → Aktivitas Tambang',
                        'shot' => 'mining/activity.png',
                        'purpose' => 'Mencatat kegiatan harian tambang: site, pit, shift, alat, operator, material, trip, tonase, dan jam kerja.',
                        'steps' => ['Klik Catat Aktivitas.', 'Pilih perusahaan, site, pit, tanggal, shift, jenis.', 'Pilih peralatan, operator, material, stockpile tujuan.', 'Isi trip dan tonase.', 'Simpan → Ajukan → (approver) Setujui → Posting ke Stok.'],
                        'fields' => ['Jenis' => 'Penambangan/Hauling/Pembersihan/Drilling/Lainnya.', 'Tonase' => 'Tonase material (Ton).', 'Stockpile Tujuan' => 'Gudang tempat material masuk saat posting.'],
                        'buttons' => ['Simpan' => 'Simpan DRAFT.', 'Ajukan' => 'Kirim ke approval.', 'Setujui' => 'Approver mengesahkan.', 'Posting ke Stok' => 'Tonase masuk stockpile via stock ledger.'],
                        'workflow' => 'DRAFT → SUBMITTED → APPROVED → POSTED.',
                        'expected' => 'Stok material bertambah sesuai tonase; hanya DRAFT yang bisa diubah/dihapus.',
                        'errors' => ['Tidak bisa posting' => 'Material & stockpile tujuan wajib diisi; status harus APPROVED.'],
                        'tips' => ['Catat harian agar tren dashboard akurat.'],
                        'related' => [['Timbangan', '/docs/weighbridge/tickets'], ['Produksi Crusher', '/docs/production/batches']],
                        'keywords' => 'tambang aktivitas tonase pit shift excavator hauling posting',
                    ],
                ],
            ],
            'weighbridge' => [
                'title' => 'Timbangan',
                'pages' => [
                    'tickets' => [
                        'title' => 'Tiket Timbangan',
                        'module' => 'Operasi Tambang → Timbangan',
                        'permission' => 'weighbridge.view (override: weighbridge.update, void: weighbridge.void)',
                        'nav' => 'Operasi Tambang → Timbangan',
                        'shot' => 'weighbridge/tickets.png',
                        'purpose' => 'Penimbangan dua tahap kendaraan keluar/masuk dengan perhitungan NET = GROSS − TARE, kalibrasi, dan audit cetak/void.',
                        'steps' => ['Klik Timbang Pertama: pilih timbangan, arah, perusahaan/site, nopol, berat terbaca → Simpan.', 'Setelah loading, buka tiket → isi berat kedua + customer/item → Simpan Timbang Kedua (NET otomatis).', 'Posting bila perlu, Cetak Tiket untuk supir.'],
                        'fields' => ['Arah' => 'Keluar (muat) atau Masuk (terima).', 'NETTO' => 'GROSS − TARE (kg).', 'Kalibrasi' => 'Versi kalibrasi aktif tercatat di tiket.'],
                        'buttons' => ['Timbang Pertama' => 'Buat tiket.', 'Simpan Timbang Kedua' => 'Selesaikan NET.', 'Posting' => 'Kunci tiket.', 'Cetak Tiket' => 'Struk untuk supir (reprint diaudit).', 'Override' => 'Koreksi berat (wajib alasan, ter-audit).', 'Void' => 'Batalkan (wajib alasan; bisa lewat approval).'],
                        'workflow' => 'FIRST_WEIGH → COMPLETE → POSTED; VOID/CANCELLED bila dibatalkan.',
                        'expected' => 'NET akurat; tiket posted tidak bisa diubah langsung.',
                        'errors' => ['Berat kedua sama' => 'Ditolak; pastikan kendaraan sudah loading/unloading.', 'Tare > gross' => 'Ditolak saat override.'],
                        'tips' => ['Pastikan kalibrasi belum kedaluwarsa sebelum shift.'],
                        'related' => [['Surat Jalan', '/docs/sales/delivery-orders'], ['Aktivitas Tambang', '/docs/mining/activity']],
                        'keywords' => 'timbangan weighbridge tiket netto gross tare kalibrasi void cetak',
                    ],
                ],
            ],
            'production' => [
                'title' => 'Produksi Crusher',
                'pages' => [
                    'batches' => [
                        'title' => 'Batch Produksi',
                        'module' => 'Operasi Tambang → Produksi Crusher',
                        'permission' => 'production.view (approve: production.approve, post: production.post)',
                        'nav' => 'Operasi Tambang → Produksi Crusher',
                        'shot' => 'production/batches.png',
                        'purpose' => 'Mencatat batch crusher: input material → output produk → loss → scrap, dengan NET = GROSS − LOSS − SCRAP otomatis.',
                        'steps' => ['Klik Batch Baru.', 'Pilih crusher, tanggal, shift, operator, jam mulai/selesai.', 'Tambah baris Input Material (ton).', 'Tambah baris Output Produk (ton).', 'Tambah Loss (debu/moisture/waste/dll) & scrap bila ada.', 'Simpan → Ajukan → Setujui → Posting (Stok + Jurnal).'],
                        'fields' => ['Loss' => 'DEBU/MOISTURE/WASTE/PROCESS_LOSS/ADJUSTMENT.', 'Net Output' => 'Gross − loss − scrap (proporsional per output).'],
                        'buttons' => ['Simpan/Ajukan/Setujui' => 'Alur dokumen.', 'Posting' => 'Stok raw keluar, FG masuk (moving average), jurnal Dr FG/Cr Raw.'],
                        'workflow' => 'DRAFT → SUBMITTED → APPROVED → POSTED.',
                        'expected' => 'Stok produk bertambah sebesar net output; loss terserap ke biaya FG.',
                        'errors' => ['Warehouse belum dikonfigurasi' => 'Isi gudang per baris atau gudang default crusher.', 'Stok tidak cukup' => 'Pastikan material tersedia di gudang sumber.'],
                        'tips' => ['Pisahkan loss debu vs moisture untuk analisis crop.'],
                        'related' => [['Saldo Stok', '/docs/inventory/stock-balance'], ['Aktivitas Tambang', '/docs/mining/activity']],
                        'keywords' => 'crusher produksi batch loss scrap net output',
                    ],
                ],
            ],
            'inventory' => [
                'title' => 'Inventory',
                'pages' => [
                    'items' => [
                        'title' => 'Master Item',
                        'module' => 'Inventory → Master Item',
                        'permission' => 'inventory.view',
                        'nav' => 'Inventory & Pengadaan → Master Item',
                        'shot' => 'inventory/items.png',
                        'purpose' => 'Master barang: produk, bahan baku, sparepart, consumable, BBM — lengkap dengan satuan, stok minimum, dan harga standar.',
                        'steps' => ['Buka Master Item.', 'Klik Tambah.', 'Isi kode, nama, kategori, tipe, satuan.', 'Isi min. stok & reorder point bila perlu.', 'Simpan.'],
                        'fields' => ['Tipe' => 'PRODUCT/RAW/SPAREPART/CONSUMABLE/FUEL/GENERAL.', 'Min. Stok' => 'Pemicu peringatan stok kritis.', 'Harga Standar' => 'Acuan awal biaya.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Item dipakai di seluruh transaksi stok.',
                        'expected' => 'Item tersedia di dropdown transaksi.',
                        'errors' => ['Kode duplikat' => 'Gunakan kode unik.'],
                        'tips' => ['Set min. stok sparepart kritis agar tidak kehabisan.'],
                        'related' => [['Saldo Stok', '/docs/inventory/stock-balance'], ['Gudang', '/docs/inventory/warehouses']],
                        'keywords' => 'item barang material produk sparepart satuan',
                    ],
                    'warehouses' => [
                        'title' => 'Gudang & Stockpile',
                        'module' => 'Inventory → Gudang',
                        'permission' => 'inventory.view',
                        'nav' => 'Inventory & Pengadaan → Gudang & Stockpile',
                        'shot' => 'inventory/warehouses.png',
                        'purpose' => 'Master lokasi penyimpanan: gudang, stockpile, stok crusher.',
                        'steps' => ['Buka Gudang & Stockpile.', 'Klik Tambah.', 'Pilih perusahaan/site, tipe, kode/nama.', 'Simpan.'],
                        'fields' => ['Tipe' => 'WAREHOUSE/STOCKPILE/CRUSHER_STOCK.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Semua pergerakan stok selalu menyebut gudang.',
                        'expected' => 'Gudang tampil di seluruh form stok.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Saldo Stok', '/docs/inventory/stock-balance']],
                        'keywords' => 'gudang warehouse stockpile lokasi',
                    ],
                    'stock-balance' => [
                        'title' => 'Saldo Stok',
                        'module' => 'Inventory → Saldo Stok',
                        'permission' => 'stock.view',
                        'nav' => 'Inventory & Pengadaan → Saldo Stok',
                        'shot' => 'inventory/stock-balance.png',
                        'purpose' => 'Melihat saldo per item per gudang yang dihitung dari stock ledger (SUM masuk − keluar) — bukan angka yang bisa diedit.',
                        'steps' => ['Buka Saldo Stok.', 'Filter gudang/cari item bila perlu.', 'Klik Kartu Stok untuk rincian pergerakan.'],
                        'fields' => ['Saldo' => 'Hasil ledger; merah bila negatif.', 'Nilai' => 'Estimasi nilai persediaan.'],
                        'buttons' => ['Kartu Stok' => 'Rincian mutasi + saldo berjalan.'],
                        'workflow' => 'Read-only; perubahan hanya via transaksi.',
                        'expected' => 'Angka konsisten dengan kartu stok & laporan.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Kartu Stok', '/docs/inventory/stock-card'], ['Transfer Stok', '/docs/inventory/stock-transfers']],
                        'keywords' => 'saldo stok balance ledger mutasi',
                    ],
                    'stock-card' => [
                        'title' => 'Kartu Stok',
                        'module' => 'Inventory → Kartu Stok',
                        'permission' => 'stock.view',
                        'nav' => 'Inventory & Pengadaan → Kartu Stok',
                        'shot' => 'inventory/stock-card.png',
                        'purpose' => 'Buku besar per item: setiap mutasi masuk/keluar dengan referensi dokumen dan saldo berjalan.',
                        'steps' => ['Buka Kartu Stok.', 'Pilih item (+ gudang/periode opsional).', 'Klik Filter.'],
                        'fields' => ['Tipe' => 'OPENING/PURCHASE/PRODUCTION/SALE/TRANSFER/ADJUSTMENT/dll.', 'Ref' => 'Nomor dokumen sumber (klik di modul asalnya).'],
                        'buttons' => ['Filter' => 'Terapkan pilihan.'],
                        'workflow' => 'Append-only: baris tidak bisa diubah.',
                        'expected' => 'Saldo akhir = saldo di halaman Saldo Stok.',
                        'errors' => [],
                        'tips' => ['Gunakan untuk audit selisih stok.'],
                        'related' => [['Saldo Stok', '/docs/inventory/stock-balance']],
                        'keywords' => 'kartu stok mutasi history ref',
                    ],
                    'stock-transfers' => [
                        'title' => 'Transfer Stok',
                        'module' => 'Inventory → Transfer',
                        'permission' => 'stock.view (posting: stock.post)',
                        'nav' => 'Inventory & Pengadaan → Transfer Stok',
                        'shot' => 'inventory/stock-transfers.png',
                        'purpose' => 'Memindahkan stok antar gudang (keluar di asal + masuk di tujuan dalam satu posting).',
                        'steps' => ['Klik Buat Transfer.', 'Pilih gudang asal & tujuan, tanggal.', 'Tambah baris item + qty.', 'Simpan → Posting.'],
                        'fields' => ['Dari/Ke' => 'Harus berbeda.'],
                        'buttons' => ['Simpan' => 'DRAFT.', 'Posting' => 'Eksekusi mutasi ganda.'],
                        'workflow' => 'DRAFT → POSTED (TRANSFER_OUT + TRANSFER_IN).',
                        'expected' => 'Saldo asal berkurang, tujuan bertambah sama besar.',
                        'errors' => ['Stok tidak cukup' => 'Kurangi qty atau tambah stok asal dulu.'],
                        'tips' => [],
                        'related' => [['Penyesuaian Stok', '/docs/inventory/stock-adjustments']],
                        'keywords' => 'transfer mutasi gudang pindah',
                    ],
                    'stock-adjustments' => [
                        'title' => 'Penyesuaian & Opname',
                        'module' => 'Inventory → Penyesuaian',
                        'permission' => 'stock.view (posting: stock.post)',
                        'nav' => 'Inventory & Pengadaan → Penyesuaian Stok',
                        'shot' => 'inventory/stock-adjustments.png',
                        'purpose' => 'Stock opname: bandingkan hasil hitung fisik vs sistem, selisih diposting sebagai adjustment ber-alasan.',
                        'steps' => ['Klik Stock Opname/Penyesuaian.', 'Pilih gudang & tanggal.', 'Isi qty hasil hitung per item.', 'Isi alasan (wajib).', 'Simpan → Posting.'],
                        'fields' => ['System vs Hitung' => 'Selisih dihitung otomatis.', 'Alasan' => 'Wajib untuk audit.'],
                        'buttons' => ['Simpan' => 'DRAFT.', 'Posting' => 'Terapkan selisih ke ledger.'],
                        'workflow' => 'DRAFT → POSTED (ADJUSTMENT_PLUS/MINUS).',
                        'expected' => 'Saldo = hasil hitung fisik.',
                        'errors' => [],
                        'tips' => ['Opname rutin per gudang tiap bulan.'],
                        'related' => [['Kartu Stok', '/docs/inventory/stock-card']],
                        'keywords' => 'opname penyesuaian adjustment selisih fisik',
                    ],
                ],
            ],
            'procurement' => [
                'title' => 'Pengadaan',
                'pages' => [
                    'purchase-requests' => [
                        'title' => 'Permintaan Pembelian (PR)',
                        'module' => 'Pengadaan → PR',
                        'permission' => 'purchase_request.view (approve: purchase_request.approve)',
                        'nav' => 'Inventory & Pengadaan → Permintaan Beli',
                        'shot' => 'procurement/purchase-requests.png',
                        'purpose' => 'Pengajuan kebutuhan barang yang wajib disetujui (matriks nominal) sebelum menjadi PO. PR tidak mengubah stok.',
                        'steps' => ['Klik Buat PR.', 'Isi perusahaan/site, tanggal, kebutuhan.', 'Tambah baris item + qty + keterangan.', 'Simpan → Ajukan.', 'Approver menyetujui sesuai nominal.'],
                        'fields' => ['Dibutuhkan Tgl' => 'Target kedatangan.', 'Matriks' => '<10jt Site Manager, 10–100jt GM, >100jt Direktur.'],
                        'buttons' => ['Simpan/Ajukan/Setujui' => 'Alur dokumen.'],
                        'workflow' => 'DRAFT → SUBMITTED → APPROVED → dipakai PO.',
                        'expected' => 'PR approved bisa dipilih saat buat PO.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Order Pembelian', '/docs/procurement/purchase-orders'], ['Pusat Persetujuan', '/docs/approval/center']],
                        'keywords' => 'pr purchase request permintaan approval',
                    ],
                    'purchase-orders' => [
                        'title' => 'Order Pembelian (PO)',
                        'module' => 'Pengadaan → PO',
                        'permission' => 'purchase_order.view (approve: purchase_order.approve)',
                        'nav' => 'Inventory & Pengadaan → Order Pembelian',
                        'shot' => 'procurement/purchase-orders.png',
                        'purpose' => 'Order resmi ke supplier (bisa dari PR). PO tidak mengubah stok — stok berubah saat GRN.',
                        'steps' => ['Klik Buat PO.', 'Pilih supplier (+ PR bila ada).', 'Isi item, qty, harga (total otomatis + PPN).', 'Isi biaya lain bila ada.', 'Simpan → (approver) Setujui.'],
                        'fields' => ['Biaya Lain' => 'Freight/admin (landed cost).', 'Total' => 'Subtotal + PPN + biaya lain.'],
                        'buttons' => ['Simpan/Setujui' => 'Alur dokumen.'],
                        'workflow' => 'DRAFT → APPROVED → dipakai GRN.',
                        'expected' => 'PO approved bisa dipilih di GRN & tagihan.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Penerimaan Barang', '/docs/procurement/goods-receipts']],
                        'keywords' => 'po purchase order supplier harga',
                    ],
                    'goods-receipts' => [
                        'title' => 'Penerimaan Barang (GRN)',
                        'module' => 'Pengadaan → GRN',
                        'permission' => 'goods_receipt.view (posting: goods_receipt.post)',
                        'nav' => 'Inventory & Pengadaan → Penerimaan Barang',
                        'shot' => 'procurement/goods-receipts.png',
                        'purpose' => 'Pencatatan barang datang dari PO + QC; saat posting, stok bertambah.',
                        'steps' => ['Klik Buat GRN.', 'Pilih PO (item termuat otomatis).', 'Pilih gudang, tanggal, status QC.', 'Isi qty diterima & diterima-baik.', 'Simpan → Posting.'],
                        'fields' => ['Diterima vs Baik' => 'Hanya qty baik yang masuk stok.', 'QC' => 'Lolos/Pending/Gagal.'],
                        'buttons' => ['Simpan' => 'DRAFT.', 'Posting' => 'Stok bertambah (PURCHASE).'],
                        'workflow' => 'DRAFT → POSTED.',
                        'expected' => 'Stok + moving average ter-update.',
                        'errors' => ['Melebihi sisa PO' => 'Qty diterima dibatasi sisa PO (anti over-receipt).', 'Item tidak ada di PO' => 'Tambahkan dulu ke PO.'],
                        'tips' => [],
                        'related' => [['Tagihan Vendor', '/docs/procurement/vendor-bills']],
                        'keywords' => 'grn penerimaan qc datang gudang',
                    ],
                    'vendor-bills' => [
                        'title' => 'Tagihan Vendor',
                        'module' => 'Pengadaan → Tagihan',
                        'permission' => 'vendor_bill.view (posting: vendor_bill.post)',
                        'nav' => 'Inventory & Pengadaan → Tagihan Vendor',
                        'shot' => 'procurement/vendor-bills.png',
                        'purpose' => 'Tagihan supplier: baris ber-item = inventory cost, baris tanpa item = beban administrasi (terpisah). Posting membentuk hutang + jurnal.',
                        'steps' => ['Klik Buat Tagihan.', 'Pilih supplier (+ PO/GRN bila ada).', 'Tambah baris item atau deskripsi beban.', 'Simpan → Posting (jurnal AP).', 'Bayar (penuh/parsial).'],
                        'fields' => ['Baris item' => 'Masuk inventory cost.', 'Baris deskripsi' => 'Masuk beban administrasi.'],
                        'buttons' => ['Simpan/Posting/Bayar' => 'Alur tagihan.'],
                        'workflow' => 'DRAFT → POSTED → PARTIALLY_PAID → PAID. Jurnal: Dr Inventory/Admin/PPN, Cr AP.',
                        'expected' => 'Hutang tercatat & berkurang saat dibayar.',
                        'errors' => ['Subtotal melebihi PO' => 'Sesuaikan dengan PO (anti over-billing).', 'Bayar melebihi outstanding' => 'Ditolak sistem.'],
                        'tips' => [],
                        'related' => [['Umur Utang', '/docs/finance/ap-aging']],
                        'keywords' => 'tagihan vendor bill hutang ap bayar',
                    ],
                ],
            ],
        ];
    }
}
