<?php

namespace App\Docs\Content;

/**
 * Konten dokumentasi — dikelompokkan per bagian.
 * Setiap halaman: title, module, permission, nav, shot, purpose,
 * steps[], fields{}, buttons{}, workflow, expected, errors[], tips[],
 * related[[label,url]], keywords.
 */
class Part1
{
    public static function pages(): array
    {
        return [
            'getting-started' => [
                'title' => 'Mulai Menggunakan',
                'pages' => [
                    'login' => [
                        'title' => 'Login ke Mining ERP',
                        'module' => 'Autentikasi',
                        'permission' => '— (halaman publik login)',
                        'nav' => 'Buka aplikasi → /login',
                        'shot' => 'dashboard/login.png',
                        'purpose' => 'Masuk ke aplikasi dengan akun yang terdaftar. Mendukung login memakai username atau email.',
                        'steps' => ['Buka alamat aplikasi di browser (mis. http://miningerp.test/login).', 'Isi Username/Email dan Password.', 'Klik tombol Login.', 'Jika password sementara, sistem meminta ganti password lebih dulu.'],
                        'fields' => ['Username/Email' => 'Username atau alamat email akun.', 'Password' => 'Password akun (case-sensitive).', 'Ingat Saya' => 'Opsional: biarkan sesi login lebih lama.'],
                        'buttons' => ['Login' => 'Verifikasi kredensial dan masuk ke dashboard.'],
                        'workflow' => 'LOGIN → DASHBOARD. 5x gagal → akun terkunci sementara.',
                        'expected' => 'Masuk ke Dashboard Eksekutif dengan menu sesuai peran.',
                        'errors' => ['Kredensial salah' => 'Periksa caps-lock dan pastikan akun ACTIVE.', 'Akun terkunci' => 'Tunggu masa kunci berakhir atau hubungi admin (Unlock).', 'Akun tidak aktif' => 'Minta admin mengaktifkan kembali (INACTIVE/SUSPENDED).'],
                        'tips' => ['Gunakan username agar mudah diingat.', 'Segera ganti password sementara setelah reset oleh admin.'],
                        'related' => [['Dashboard', '/docs/getting-started/dashboard'], ['Manajemen Pengguna', '/docs/administration/users']],
                        'keywords' => 'login masuk username password terkunci akun',
                    ],
                    'dashboard' => [
                        'title' => 'Dashboard Eksekutif',
                        'module' => 'Dashboard',
                        'permission' => 'dashboard.view',
                        'nav' => 'Login → Dashboard',
                        'shot' => 'dashboard/dashboard.png',
                        'purpose' => 'Satu layar berisi ringkasan operasional, penjualan, keuangan, HR, maintenance, dan persetujuan — semuanya dari data database nyata.',
                        'steps' => ['Setelah login, dashboard tampil otomatis.', 'Gunakan filter Site dan Periode untuk mempersempit angka.', 'Klik kartu/chart untuk melihat detail tren.', 'Cek panel Persetujuan Tertunda untuk tugas approval.'],
                        'fields' => ['Filter Site' => 'Batasi seluruh widget ke satu site.', 'Filter Periode' => 'Rentang tanggal perhitungan widget.'],
                        'buttons' => ['Lihat semua (approval)' => 'Membuka Pusat Persetujuan.'],
                        'workflow' => 'Data mengalir otomatis dari modul transaksi (tanpa input manual).',
                        'expected' => 'Angka produksi, penjualan, kas, karyawan, WO terbuka, dan stok kritis terkini.',
                        'errors' => ['Angka 0 semua' => 'Belum ada transaksi pada periode/site terpilih; ubah filter.', 'Chart tidak tampil' => 'Pastikan koneksi internet untuk CDN chart atau bundle lokal termuat.'],
                        'tips' => ['Manager site cukup filter site-nya untuk fokus pada areanya.', 'Stok kritis berwarna merah perlu tindak lanjut pembelian.'],
                        'related' => [['Laporan Produksi Tambang', '/docs/reports/mining'], ['Pusat Persetujuan', '/docs/approval/center']],
                        'keywords' => 'dashboard widget grafik produksi penjualan kas statistik',
                    ],
                    'navigasi' => [
                        'title' => 'Navigasi Aplikasi',
                        'module' => 'Antarmuka',
                        'permission' => 'dashboard.view',
                        'nav' => 'Seluruh aplikasi',
                        'purpose' => 'Sidebar menampilkan menu sesuai izin peran; topbar berisi pencarian global (Ctrl+K), bantuan kontekstual, persetujuan, notifikasi, dan menu pengguna.',
                        'steps' => ['Gunakan grup sidebar untuk berpindah modul (klik untuk buka/tutup).', 'Tekan Ctrl+K lalu ketik untuk lompat ke halaman atau cari transaksi.', 'Klik ikon ? di topbar untuk membuka panduan halaman yang sedang dibuka.', 'Klik avatar untuk Profil, Keamanan, Dokumentasi, dan Keluar.'],
                        'fields' => ['Sidebar' => 'Menu dikelompokkan; badge hanya untuk item berizin.', 'Ctrl+K' => 'Palet perintah: aksi cepat + pencarian global.', '? Bantuan' => 'Membuka halaman docs sesuai route aktif.'],
                        'buttons' => ['Ciutkan sidebar' => 'Mode ikon 76px; preferensi tersimpan di browser.', 'Cetak' => 'Mencetak halaman (area navigasi disembunyikan otomatis).'],
                        'workflow' => 'LOGIN → DASHBOARD → modul via sidebar/pencarian.',
                        'expected' => 'Berpindah halaman dalam 1–2 klik; bantuan selalu satu klik.',
                        'errors' => ['Menu tidak ada' => 'Peran tidak punya izin modul tersebut; hubungi admin.', 'Pencarian kosong' => 'Gunakan kata kunci lain atau buka modul langsung.'],
                        'tips' => ['Hafalkan Ctrl+K — jauh lebih cepat daripada klik menu.', 'Di layar kecil, sidebar menjadi drawer geser.'],
                        'related' => [['Dashboard Eksekutif', '/docs/getting-started/dashboard'], ['Manajemen Pengguna', '/docs/administration/users']],
                        'keywords' => 'navigasi sidebar topbar pencarian ctrl+k bantuan menu',
                    ],
                    'data-scope' => [
                        'title' => 'Data Scope & Batasan Akses',
                        'module' => 'Keamanan Data',
                        'permission' => 'Semua peran (diterapkan otomatis)',
                        'nav' => 'Otomatis per peran',
                        'purpose' => 'Selain izin menu, setiap peran dibatasi scope data: seluruh perusahaan, per company, per site, atau data sendiri. Akses ID record di luar scope ditolak (403) walau URL ditebak.',
                        'steps' => ['Admin menentukan scope saat assign peran ke user.', 'Buka halaman daftar: baris otomatis difilter sesuai scope.', 'Mencoba membuka record luar scope menghasilkan halaman 403.', 'Minta admin meluaskan scope bila pekerjaan membutuhkan.'],
                        'fields' => ['ALL' => 'Melihat seluruh data (direksi, super admin).', 'COMPANY/SITE' => 'Terbatas pada company/site penugasan.', 'OWN_DATA' => 'Hanya data yang dibuat sendiri.'],
                        'buttons' => [],
                        'workflow' => 'Assign peran + scope → filter otomatis di semua daftar.',
                        'expected' => 'User site A tidak pernah melihat data site B.',
                        'errors' => ['403 Data di luar scope' => 'Wajar: record milik scope lain.', 'Daftar kosong' => 'Scope terlalu sempit atau belum ada data di scope tersebut.'],
                        'tips' => ['Auditor: uji akses silang site untuk memastikan isolasi.'],
                        'related' => [['Manajemen Pengguna', '/docs/administration/users'], ['Manajemen Peran', '/docs/administration/roles']],
                        'keywords' => 'data scope site company own data 403 idor isolasi',
                    ],
                    'notifikasi' => [
                        'title' => 'Notifikasi & Peringatan',
                        'module' => 'Notifikasi',
                        'permission' => 'Otomatis per peran',
                        'nav' => 'Topbar → ikon lonceng',
                        'purpose' => 'Peringatan proaktif (stok kritis, faktur overdue, izin kedaluwarsa, anomali BBM, dsb.) dikirim ke peran terkait setiap pagi oleh scheduler.',
                        'steps' => ['Klik ikon lonceng di topbar untuk 10 notifikasi terbaru.', 'Klik notifikasi untuk detail (jika ada tautan).', 'Aturan ambang diatur admin di Pengaturan Sistem.', 'Jalankan php artisan alert:scan untuk cek manual.'],
                        'fields' => ['Kritis vs biasa' => 'Peringatan kritis tampil menonjol (merah).', 'Jadwal' => 'Pemindaian harian 07:00 + pengingat compliance H-90/60/30/14/7.'],
                        'buttons' => ['Tandai dibaca' => 'Membersihkan daftar notifikasi.'],
                        'workflow' => 'Scheduler → pindai kondisi → kirim ke peran → lonceng topbar.',
                        'expected' => 'Masalah penting diketahui sebelum menjadi darurat.',
                        'errors' => ['Tidak ada notifikasi' => 'Belum ada kondisi terpicu atau peran tidak termasuk penerima.'],
                        'tips' => ['Jangan abaikan badge merah persetujuan & notifikasi setiap pagi.'],
                        'related' => [['Dashboard Eksekutif', '/docs/getting-started/dashboard']],
                        'keywords' => 'notifikasi peringatan alert lonceng scheduler kritis',
                    ],
                ],
            ],
            'administration' => [
                'title' => 'Administrasi',
                'pages' => [
                    'users' => [
                        'title' => 'Manajemen Pengguna',
                        'module' => 'Administrasi → Manajemen Pengguna',
                        'permission' => 'user.view (aksi: user.create/update, role.update untuk peran)',
                        'nav' => 'Administrasi → Manajemen Pengguna',
                        'shot' => 'administration/users.png',
                        'purpose' => 'Mengelola akun pengguna: tambah, edit, aktif/nonaktif, reset password, buka kunci, atur peran, lihat riwayat login, dan akhiri semua sesi.',
                        'steps' => ['Buka Administrasi → Manajemen Pengguna.', 'Klik Tambah Pengguna.', 'Isi nama, username, email (unik).', 'Tentukan role (perlu izin role.update).', 'Tentukan company/site scope bila perlu.', 'Klik Simpan.'],
                        'fields' => ['Nama/Username/Email' => 'Identitas akun; username & email harus unik.', 'Status' => 'ACTIVE, INACTIVE, SUSPENDED, LOCKED.', 'Peran' => 'Menentukan hak akses; butuh izin role.update.', 'Scope' => 'ALL_COMPANIES, COMPANY, SITE, OWN_DATA.'],
                        'buttons' => ['Tambah' => 'Form pengguna baru.', 'Edit' => 'Ubah data pengguna.', 'Aktif/Nonaktif' => 'Toggle status akun.', 'Reset Password' => 'Buat password sementara + wajib ganti saat login.', 'Unlock' => 'Buka akun terkunci.', 'Login History' => 'Riwayat LOGIN/LOGOUT/FAILED/LOCKOUT + IP.', 'Logout All' => 'Akhiri semua sesi perangkat.'],
                        'workflow' => 'CREATE → ACTIVE. Gagal login 5x → LOCKED. Reset → FORCE_PASSWORD_RESET.',
                        'expected' => 'Pengguna baru bisa login sesuai perannya; menu otomatis mengikuti izin.',
                        'errors' => ['403 saat assign role' => 'Butuh izin role.update, bukan hanya user.update.', 'Tidak bisa nonaktifkan diri' => 'Sistem mencegah sebagai pengaman (gunakan admin lain).', 'Username sudah dipakai' => 'Gunakan username unik.'],
                        'tips' => ['Jangan memberi SUPER_ADMIN kecuali darurat.', 'Cek Login History bila ada laporan akses aneh.'],
                        'related' => [['Manajemen Peran', '/docs/administration/roles'], ['Login', '/docs/getting-started/login']],
                        'keywords' => 'user pengguna tambah reset password unlock role scope aktif nonaktif login history',
                    ],
                    'roles' => [
                        'title' => 'Manajemen Peran & Matriks Izin',
                        'module' => 'Administrasi → Manajemen Peran',
                        'permission' => 'role.view (ubah: role.update)',
                        'nav' => 'Administrasi → Manajemen Peran',
                        'shot' => 'administration/roles.png',
                        'purpose' => 'Mendefinisikan peran dan matriks izin granular per modul × aksi (view/create/update/delete/approve/post/dll).',
                        'steps' => ['Buka Administrasi → Manajemen Peran.', 'Klik Matriks Izin pada peran.', 'Centang izin per modul × aksi.', 'Simpan Matriks.', 'Uji dengan login sebagai user peran tersebut.'],
                        'fields' => ['Kode/Nama' => 'Identitas peran (cth. SALES, WAREHOUSE_STAFF).', 'Sistem' => 'Peran bawaan yang tidak bisa dihapus.'],
                        'buttons' => ['Tambah' => 'Buat peran baru.', 'Matriks Izin' => 'Editor centang izin.', 'Simpan Matriks' => 'Terapkan izin (berlaku segera).', 'Hapus' => 'Hapus peran non-sistem.'],
                        'workflow' => 'Role → Permission → Menu + Data Scope + Approval Authority.',
                        'expected' => 'Menu sidebar user berubah mengikuti izin; endpoint tanpa izin mengembalikan 403.',
                        'errors' => ['Menu hilang setelah ubah' => 'Izin view modul belum dicentang.', 'Aksi 403' => 'Izin aksi (approve/post/dll) belum diberikan.'],
                        'tips' => ['Prinsip least-privilege: beri izin minimum yang dibutuhkan.', 'AUDITOR/VIEWER hanya view+export+print.'],
                        'related' => [['Manajemen Pengguna', '/docs/administration/users'], ['Audit Trail', '/docs/administration/audit']],
                        'keywords' => 'role peran permission matriks izin hak akses matrix',
                    ],
                    'audit' => [
                        'title' => 'Audit Trail',
                        'module' => 'Administrasi → Audit Trail',
                        'permission' => 'audit.view',
                        'nav' => 'Administrasi → Audit Trail',
                        'shot' => 'administration/audit.png',
                        'purpose' => 'Jejak audit tak-terhapuskan atas semua aksi penting: siapa, kapan, apa, nilai lama/baru, IP, dan alasan.',
                        'steps' => ['Buka Administrasi → Audit Trail.', 'Filter modul/aksi/periode bila perlu.', 'Klik baris untuk melihat old vs new values.'],
                        'fields' => ['Aksi' => 'CREATE/UPDATE/DELETE/SUBMIT/APPROVE/REJECT/POST/PRINT/EXPORT/VOID/LOGIN/dll.', 'Record' => 'Tipe + ID data yang berubah.'],
                        'buttons' => ['Filter' => 'Saring modul/aksi/periode.', 'Reset' => 'Kembalikan filter.'],
                        'workflow' => 'Setiap aksi transaksional otomatis mencatat audit (tidak bisa dihapus user biasa).',
                        'expected' => 'Riwayat lengkap perubahan data penting.',
                        'errors' => [],
                        'tips' => ['Gunakan audit untuk investigasi selisih stok/kas.'],
                        'related' => [['Manajemen Pengguna', '/docs/administration/users']],
                        'keywords' => 'audit trail log aktivitas history jejak',
                    ],
                    'settings' => [
                        'title' => 'Pengaturan Sistem',
                        'module' => 'Administrasi → Pengaturan',
                        'permission' => 'setting.view (ubah: setting.update)',
                        'nav' => 'Administrasi → Pengaturan Sistem',
                        'shot' => 'administration/settings.png',
                        'purpose' => 'Konfigurasi perilaku sistem tanpa ubah kode: pajak, payroll, timbangan, inventory, notifikasi WhatsApp, visibilitas dokumentasi.',
                        'steps' => ['Buka Pengaturan Sistem.', 'Ubah nilai yang perlu.', 'Simpan Pengaturan.'],
                        'fields' => ['inventory.allow_negative_stock' => 'Izinkan stok minus (default false).', 'payroll.ptkp_monthly / pph21_rate' => 'Parameter PPh 21.', 'tax.default_sales_tax_code' => 'Kode pajak default faktur.', 'weighbridge.allow_weight_override' => 'Aktif/nonaktif override berat.', 'notification.whatsapp_webhook_url' => 'Webhook WhatsApp (kosong = nonaktif).', 'docs.public' => 'Dokumentasi /docs tanpa login bila true.'],
                        'buttons' => ['Simpan Pengaturan' => 'Terapkan konfigurasi.'],
                        'workflow' => 'Perubahan berlaku segera untuk transaksi berikutnya.',
                        'expected' => 'Perilaku sistem mengikuti konfigurasi.',
                        'errors' => ['Tarif pajak salah di faktur lama' => 'Perubahan tarif hanya berlaku untuk transaksi baru.'],
                        'tips' => ['Dokumentasikan setiap perubahan setting penting.'],
                        'related' => [['Pajak', '/docs/finance/tax'], ['Payroll', '/docs/hr/payroll']],
                        'keywords' => 'setting pengaturan konfigurasi pajak payroll whatsapp docs',
                    ],
                ],
            ],
            'organization' => [
                'title' => 'Organisasi',
                'pages' => [
                    'companies' => [
                        'title' => 'Perusahaan',
                        'module' => 'Organisasi → Perusahaan',
                        'permission' => 'company.view',
                        'nav' => 'Organisasi → Perusahaan',
                        'shot' => 'organization/companies.png',
                        'purpose' => 'Master perusahaan (multi-company) sebagai scope tertinggi seluruh transaksi.',
                        'steps' => ['Buka Organisasi → Perusahaan.', 'Klik Tambah.', 'Isi kode, nama, NPWP, alamat, kota, telepon, email.', 'Simpan.'],
                        'fields' => ['Kode' => 'Unik per sistem.', 'NPWP' => 'Untuk dokumen pajak.', 'Status' => 'Aktif/nonaktif.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar (hapus = soft delete).'],
                        'workflow' => 'Company → Branch → Site → transaksi.',
                        'expected' => 'Perusahaan tampil di dropdown seluruh form transaksi.',
                        'errors' => ['Kode duplikat' => 'Gunakan kode unik.'],
                        'tips' => ['Nonaktifkan (jangan hapus) perusahaan lama agar histori aman.'],
                        'related' => [['Cabang', '/docs/organization/branches'], ['Site Tambang', '/docs/organization/sites']],
                        'keywords' => 'perusahaan company cabang site organisasi npwp',
                    ],
                    'branches' => [
                        'title' => 'Cabang',
                        'module' => 'Organisasi → Cabang',
                        'permission' => 'branch.view',
                        'nav' => 'Organisasi → Cabang',
                        'shot' => 'organization/branches.png',
                        'purpose' => 'Master cabang di bawah perusahaan.',
                        'steps' => ['Buka Organisasi → Cabang.', 'Klik Tambah, pilih perusahaan, isi kode/nama/kota.', 'Simpan.'],
                        'fields' => ['Perusahaan' => 'Induk cabang.', 'Kode/Nama/Kota' => 'Identitas cabang.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Cabang mengelompokkan site.',
                        'expected' => 'Cabang tersedia untuk site dan laporan.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Perusahaan', '/docs/organization/companies'], ['Site Tambang', '/docs/organization/sites']],
                        'keywords' => 'cabang branch',
                    ],
                    'sites' => [
                        'title' => 'Site Tambang',
                        'module' => 'Organisasi → Site Tambang',
                        'permission' => 'site.view',
                        'nav' => 'Organisasi → Site Tambang',
                        'shot' => 'organization/sites.png',
                        'purpose' => 'Master lokasi operasional (MINE/PLANT/PORT/OFFICE) — unit data scope utama.',
                        'steps' => ['Buka Organisasi → Site Tambang.', 'Klik Tambah, pilih perusahaan & tipe.', 'Simpan.'],
                        'fields' => ['Tipe' => 'MINE (tambang), PLANT, PORT, OFFICE.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Site dipakai di mining, timbangan, produksi, inventory, penjualan.',
                        'expected' => 'Site tampil di filter dashboard & seluruh transaksi.',
                        'errors' => [],
                        'tips' => ['User site cukup diberi scope SITE agar hanya melihat datanya.'],
                        'related' => [['Aktivitas Tambang', '/docs/mining/activity'], ['Dashboard', '/docs/getting-started/dashboard']],
                        'keywords' => 'site tambang lokasi mine plant port scope',
                    ],
                    'divisions' => [
                        'title' => 'Divisi & Departemen',
                        'module' => 'Organisasi → Divisi & Departemen',
                        'permission' => 'division.view',
                        'nav' => 'Organisasi → Divisi & Departemen',
                        'shot' => 'organization/divisions.png',
                        'purpose' => 'Struktur divisi/departemen untuk organisasi karyawan dan approval.',
                        'steps' => ['Buka Organisasi → Divisi & Departemen.', 'Tambah divisi lalu departemen di bawahnya.', 'Simpan.'],
                        'fields' => ['Divisi' => 'Induk departemen.', 'Departemen' => 'Unit kerja karyawan.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Karyawan & approval dapat dikelompokkan per divisi.',
                        'expected' => 'Struktur tersedia di form karyawan.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Karyawan', '/docs/hr/employees']],
                        'keywords' => 'divisi departemen struktur organisasi',
                    ],
                ],
            ],
            'hr' => [
                'title' => 'HR & Payroll',
                'pages' => [
                    'employees' => [
                        'title' => 'Karyawan',
                        'module' => 'HR → Karyawan',
                        'permission' => 'employee.view',
                        'nav' => 'HR & Payroll → Karyawan',
                        'shot' => 'hr/employees.png',
                        'purpose' => 'Master karyawan: identitas, posisi, tipe kepegawaian, shift, gaji pokok, dan rekening.',
                        'steps' => ['Buka HR → Karyawan.', 'Klik Tambah.', 'Isi NIP, nama, perusahaan/site/divisi, posisi.', 'Isi gaji pokok, bank, tanggal masuk.', 'Simpan.'],
                        'fields' => ['NIP' => 'Unik.', 'Tipe' => 'Tetap/Kontrak/Percobaan/Harian/Outsourced.', 'Gaji Pokok' => 'Basis perhitungan payroll.', 'Shift' => 'Menentukan aturan keterlambatan.'],
                        'buttons' => ['Tambah/Edit/Hapus' => 'CRUD standar.'],
                        'workflow' => 'Karyawan → Absensi → Lembur → Insentif → Payroll.',
                        'expected' => 'Karyawan aktif masuk perhitungan payroll periode berjalan.',
                        'errors' => ['Tidak masuk payroll' => 'Pastikan status ACTIVE dan tanggal masuk valid.'],
                        'tips' => ['Hubungkan user login ke data karyawan bila perlu.'],
                        'related' => [['Absensi', '/docs/hr/attendances'], ['Payroll', '/docs/hr/payroll']],
                        'keywords' => 'karyawan employee nip gaji posisi shift',
                    ],
                    'attendances' => [
                        'title' => 'Absensi & Fingerprint',
                        'module' => 'HR → Absensi',
                        'permission' => 'attendance.view',
                        'nav' => 'HR & Payroll → Absensi',
                        'shot' => 'hr/attendances.png',
                        'purpose' => 'Catat kehadiran harian manual atau import CSV fingerprint; keterlambatan dihitung otomatis dari shift.',
                        'steps' => ['Buka HR → Absensi.', 'Untuk manual: pilih karyawan, tanggal, jam, status → Simpan.', 'Untuk fingerprint: siapkan CSV (employee_code,date,check_in,check_out) → Import.'],
                        'fields' => ['Status' => 'PRESENT/LATE/ABSENT/LEAVE/SICK/HOLIDAY/OFF.', 'Telat' => 'Menit keterlambatan vs jam shift.', 'Lembur' => 'Menit lembur tercatat.'],
                        'buttons' => ['Simpan' => 'Simpan baris manual.', 'Import Fingerprint' => 'Proses file CSV.'],
                        'workflow' => 'Absensi → dasar lembur & payroll.',
                        'expected' => 'Rekap kehadiran per tanggal; baris dilewati bila NIP tidak cocok (dilaporkan).',
                        'errors' => ['NIP tidak ditemukan' => 'Samakan kode di mesin fingerprint dengan NIP.'],
                        'tips' => ['Import rutin harian agar payroll akurat.'],
                        'related' => [['Lembur', '/docs/hr/overtimes'], ['Payroll', '/docs/hr/payroll']],
                        'keywords' => 'absensi fingerprint kehadiran import csv telat',
                    ],
                    'leaves' => [
                        'title' => 'Cuti',
                        'module' => 'HR → Cuti',
                        'permission' => 'leave.view',
                        'nav' => 'HR & Payroll → Cuti',
                        'shot' => 'hr/leaves.png',
                        'purpose' => 'Pengajuan dan persetujuan cuti karyawan.',
                        'steps' => ['Buka HR → Cuti → Ajukan.', 'Pilih karyawan, tipe, rentang tanggal, alasan.', 'Simpan lalu Submit.', 'Approver menyetujui/menolak.'],
                        'fields' => ['Tipe' => 'Tahunan/Sakit/Tanpa Gaji/Melahirkan/Lainnya.', 'Hari' => 'Dihitung otomatis inklusif.'],
                        'buttons' => ['Ajukan' => 'Buat pengajuan DRAFT.', 'Setujui/Tolak' => 'Keputusan approver.'],
                        'workflow' => 'DRAFT → SUBMITTED → APPROVED/REJECTED.',
                        'expected' => 'Cuti approved tercatat dan memengaruhi absensi.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Absensi', '/docs/hr/attendances']],
                        'keywords' => 'cuti leave pengajuan approval',
                    ],
                    'overtimes' => [
                        'title' => 'Lembur',
                        'module' => 'HR → Lembur',
                        'permission' => 'overtime.view',
                        'nav' => 'HR & Payroll → Lembur',
                        'shot' => 'hr/overtimes.png',
                        'purpose' => 'Catat dan setujui jam lembur; otomatis menjadi komponen upah lembur di payroll.',
                        'steps' => ['Buka HR → Lembur → Catat.', 'Pilih karyawan, tanggal, jam, alasan.', 'Simpan; approver menyetujui.'],
                        'fields' => ['Jam' => '0,5–24 jam.', 'Upah' => 'Dihitung: gaji/173 × jam × 1,5.'],
                        'buttons' => ['Simpan' => 'Catat lembur.', 'Setujui' => 'Approver mengesahkan.'],
                        'workflow' => 'DRAFT → APPROVED → masuk payroll.',
                        'expected' => 'Lembur approved menambah bruto payroll.',
                        'errors' => [],
                        'tips' => [],
                        'related' => [['Payroll', '/docs/hr/payroll']],
                        'keywords' => 'lembur overtime upah',
                    ],
                    'payroll' => [
                        'title' => 'Payroll',
                        'module' => 'HR → Payroll',
                        'permission' => 'payroll.view (approve: payroll.approve, post: payroll.post)',
                        'nav' => 'HR & Payroll → Payroll',
                        'shot' => 'hr/payroll.png',
                        'purpose' => 'Hitung gaji periodik: pokok + tunjangan + lembur + insentif − potongan − PPh21, lalu posting jurnal otomatis.',
                        'steps' => ['Buat Run Baru (perusahaan + periode YYYY-MM).', 'Klik Kalkulasi.', 'Periksa detail per karyawan.', 'Setujui.', 'Posting Jurnal.', 'Tandai Dibayar.', 'Cetak slip per karyawan (tombol Slip).'],
                        'fields' => ['Bruto' => 'Total penerimaan.', 'Potongan' => 'Termasuk PPh21 ((bruto−PTKP)×tarif).', 'Neto' => 'Diterima karyawan.'],
                        'buttons' => ['Kalkulasi' => 'Hitung ulang seluruh karyawan aktif.', 'Setujui' => 'Kunci hasil.', 'Posting Jurnal' => 'Dr Beban Gaji / Cr PPh21 & Hutang Gaji.', 'Tandai Dibayar' => 'Dr Hutang Gaji / Cr Kas.', 'Slip' => 'Cetak slip gaji.'],
                        'workflow' => 'DRAFT → CALCULATED → APPROVED → POSTED → PAID.',
                        'expected' => 'Gaji akurat + jurnal balance + slip tercetak.',
                        'errors' => ['Insentif tidak masuk' => 'Insentif harus APPROVED sebelum kalkulasi.', 'Tidak bisa posting' => 'Status harus APPROVED.'],
                        'tips' => ['Kalkulasi ulang aman (detail dihitung ulang) selama masih DRAFT/CALCULATED.'],
                        'related' => [['Insentif Operator', '/docs/hr/incentives'], ['Jurnal', '/docs/finance/journals']],
                        'keywords' => 'payroll gaji kalkulasi slip pph21 posting',
                    ],
                    'incentives' => [
                        'title' => 'Insentif Operator',
                        'module' => 'HR → Insentif Operator',
                        'permission' => 'incentive.view (approve: incentive.approve)',
                        'nav' => 'HR & Payroll → Insentif Operator',
                        'shot' => 'hr/incentives.png',
                        'purpose' => 'Insentif berbasis tonase/shift/aktivitas/alat/target. WAJIB approved sebelum masuk payroll.',
                        'steps' => ['Klik Buat Insentif.', 'Pilih karyawan, basis, periode, qty, rate.', 'Simpan (DRAFT).', 'Approver menyetujui.'],
                        'fields' => ['Basis' => 'TONNAGE/SHIFT/ACTIVITY/EQUIPMENT/TARGET.', 'Jumlah' => 'Qty × rate.'],
                        'buttons' => ['Simpan' => 'Buat DRAFT.', 'Setujui' => 'Masuk pool payroll.'],
                        'workflow' => 'DRAFT → APPROVED → INCLUDED_IN_PAYROLL.',
                        'expected' => 'Insentif approved otomatis masuk payroll periode tsb.',
                        'errors' => [],
                        'tips' => ['Samakan periode insentif dengan periode payroll.'],
                        'related' => [['Payroll', '/docs/hr/payroll'], ['Aktivitas Tambang', '/docs/mining/activity']],
                        'keywords' => 'insentif operator bonus tonase rate',
                    ],
                ],
            ],
        ];
    }
}
