<?php

namespace App\Docs\Content;

class Part5
{
    public static function pages(): array
    {
        return [
            'fleet' => [
                'title' => 'Armada & Alat Berat',
                'pages' => [
                    'dashboard' => [
                        'title' => 'Dashboard Armada',
                        'module' => 'Armada & BBM → Dashboard Armada',
                        'permission' => 'fleet.view',
                        'nav' => 'Armada & BBM → Dashboard Armada',
                        'shot' => 'fleet/dashboard.png',
                        'purpose' => 'Ringkasan kesiapan unit, status jalan/rusak/standby, HM/KM terakhir, dan konsumsi BBM per unit.',
                        'steps' => ['Buka Dashboard Armada.', 'Pilih site/periode bila tersedia.', 'Klik unit untuk melihat meter, BBM, dan WO terkait.', 'Tindak lanjuti unit boros/rusak via WO.'],
                        'fields' => ['Status Unit' => 'Jalan, standby, breakdown, atau maintenance.', 'LPH' => 'Liter per jam aktual vs standar kategori alat.'],
                        'buttons' => ['Detail Unit' => 'Buka profil unit.', 'Buat WO' => 'Buat work order dari temuan dashboard.'],
                        'workflow' => 'Meter + BBM POSTED + WO → agregat dashboard.',
                        'expected' => 'Kesiapan armada dan unit bermasalah terlihat sekilas.',
                        'errors' => ['Data kosong' => 'Pastikan meter HM/KM dan transaksi BBM sudah diinput.'],
                        'tips' => ['Pantau LPH di atas standar sebagai sinyal kebocoran atau perlu servis.'],
                        'related' => [['Meter HM/KM', '/docs/fleet/meters'], ['Work Order', '/docs/maintenance/work-orders']],
                        'keywords' => 'armada dashboard fleet alat berat kesiapan hm km lph',
                    ],
                    'meters' => [
                        'title' => 'Meter HM / KM',
                        'module' => 'Armada → Meter HM/KM',
                        'permission' => 'fleet.view',
                        'nav' => 'Armada & BBM → Meter HM/KM',
                        'shot' => 'fleet/meters.png',
                        'purpose' => 'Catat hour-meter dan kilometer unit sebagai dasar depresiasi, konsumsi BBM per jam, dan jadwal servis.',
                        'steps' => ['Buka Meter HM/KM.', 'Pilih unit dan tanggal pembacaan.', 'Isi HM awal, HM akhir, dan jam operasi.', 'Simpan pembacaan meter.'],
                        'fields' => ['HM Awal/Akhir' => 'HM akhir tidak boleh lebih kecil dari HM awal.', 'Jam Operasi' => 'Dasar hitung liter per jam (LPH).'],
                        'buttons' => ['Simpan' => 'Simpan pembacaan meter.'],
                        'workflow' => 'Input meter → dipakai validasi issue BBM + depresiasi + cost engine.',
                        'expected' => 'Riwayat meter tersimpan berurutan per unit.',
                        'errors' => ['HM akhir lebih kecil' => 'Periksa angka awal; sistem menolak pembacaan mundur.'],
                        'tips' => ['Catat meter setiap pengisian BBM agar LPH akurat.'],
                        'related' => [['Pengeluaran BBM', '/docs/fuel/issues'], ['Dashboard Armada', '/docs/fleet/dashboard']],
                        'keywords' => 'meter hm km hour meter odometer pembacaan unit',
                    ],
                    'inspections' => [
                        'title' => 'Inspeksi Harian (P2H)',
                        'module' => 'Armada → Inspeksi',
                        'permission' => 'fleet.view',
                        'nav' => 'Armada & BBM → Inspeksi Harian',
                        'shot' => 'fleet/inspections.png',
                        'purpose' => 'Checklist P2H harian per unit; temuan rusak mengarahkan ke work order agar unit tidak jalan dalam kondisi bahaya.',
                        'steps' => ['Buka Inspeksi Harian.', 'Pilih unit dan tanggal.', 'Centang item P2H dan catat temuan.', 'Buat WO bila ada temuan kritis.'],
                        'fields' => ['Hasil' => 'Lulus atau temuan; temuan kritis wajib WO.', 'Temuan' => 'Catatan kerusakan + foto bila ada.'],
                        'buttons' => ['Simpan' => 'Simpan hasil inspeksi.', 'Buat WO' => 'Eskalasi temuan ke work order.'],
                        'workflow' => 'Inspeksi → temuan → WO → unit kembali jalan.',
                        'expected' => 'Setiap unit aktif punya catatan P2H harian.',
                        'errors' => ['Duplikat tanggal' => 'Satu unit satu inspeksi aktif per tanggal; edit yang ada.'],
                        'tips' => ['Jadikan P2H syarat unit boleh dispatch hari itu.'],
                        'related' => [['Dashboard Armada', '/docs/fleet/dashboard'], ['Work Order', '/docs/maintenance/work-orders']],
                        'keywords' => 'inspeksi p2h checklist harian temuan unit',
                    ],
                    'vehicles' => [
                        'title' => 'Master Unit / Kendaraan',
                        'module' => 'Armada → Master Unit',
                        'permission' => 'fleet.view',
                        'nav' => 'Armada & BBM → Master Unit',
                        'shot' => 'fleet/vehicles.png',
                        'purpose' => 'Master alat berat dan kendaraan: kategori, standar BBM (LPH), status kepemilikan, dan depresiasi per periode.',
                        'steps' => ['Buka Master Unit.', 'Klik Tambah untuk unit baru.', 'Isi kode, kategori, standar LPH, dan site.', 'Simpan dan aktifkan unit.'],
                        'fields' => ['Standar LPH' => 'Acuan wajar konsumsi BBM per kategori alat.', 'Status' => 'Aktif, standby, breakdown, atau dijual.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola master unit.'],
                        'workflow' => 'Master unit → dipakai meter, BBM, dispatch, dan cost engine.',
                        'expected' => 'Unit tampil di form meter, BBM, dan dispatch.',
                        'errors' => ['Kode duplikat' => 'Gunakan kode unit yang unik.'],
                        'tips' => ['Isi standar LPH kategori agar variansi BBM bisa dihitung otomatis.'],
                        'related' => [['Meter HM/KM', '/docs/fleet/meters'], ['Telematics', '/docs/telematics/overview']],
                        'keywords' => 'unit kendaraan alat berat master kategori depresiasi lph',
                    ],
                ],
            ],
            'fuel' => [
                'title' => 'Manajemen BBM',
                'pages' => [
                    'dashboard' => [
                        'title' => 'Dashboard BBM',
                        'module' => 'BBM → Dashboard',
                        'permission' => 'fuel.view',
                        'nav' => 'Armada & BBM → Dashboard BBM',
                        'shot' => 'fuel/dashboard.png',
                        'purpose' => 'Pantau saldo tangki (dari fuel ledger), penerimaan vs pengeluaran POSTED 7 hari, dan unit paling boros.',
                        'steps' => ['Buka Dashboard BBM.', 'Cek saldo per tangki dari ledger.', 'Cek tren penerimaan vs pengeluaran.', 'Klik unit boros untuk rincian issue.'],
                        'fields' => ['Saldo Tangki' => 'IN − OUT dari fuel ledger, bukan input manual.', 'LPH Aktual' => 'Liter dibagi jam operasi vs standar.'],
                        'buttons' => ['Rincian' => 'Lompat ke receipt/issue terkait.'],
                        'workflow' => 'Receipt/issue POSTED → ledger → dashboard.',
                        'expected' => 'Saldo dan tren BBM sesuai transaksi POSTED.',
                        'errors' => ['Saldo tidak cocok' => 'Cek transaksi DRAFT/APPROVED yang belum POSTED.'],
                        'tips' => ['Selisih fisik vs sistem dicek lewat menu Dip Tangki.'],
                        'related' => [['Penerimaan BBM', '/docs/fuel/receipts'], ['Dip Tangki', '/docs/fuel/dips']],
                        'keywords' => 'bbm dashboard solar saldo tangki ledger konsumsi lph',
                    ],
                    'receipts' => [
                        'title' => 'Penerimaan BBM (Receipt)',
                        'module' => 'BBM → Penerimaan',
                        'permission' => 'fuel.view',
                        'nav' => 'Armada & BBM → Penerimaan BBM',
                        'shot' => 'fuel/receipts.png',
                        'purpose' => 'Terima BBM dari supplier ke tangki dengan alur DRAFT → submit → pusat approval → APPROVED → POSTED; posting menambah ledger IN dan jurnal persediaan vs hutang.',
                        'steps' => ['Buat receipt: tangki, supplier, liter, harga satuan.', 'Submit ke pusat approval (/docs/approval/center).', 'Setelah APPROVED, klik Posting.', 'Cek ledger bertambah dan jurnal terbentuk.'],
                        'fields' => ['Liter/Harga' => 'Total = liter × harga satuan.', 'Status' => 'DRAFT → APPROVED → POSTED; hanya APPROVED yang bisa posting.'],
                        'buttons' => ['Submit' => 'Kirim ke approval center.', 'Approve' => 'Setujui di pusat approval.', 'Posting' => 'Catat ledger IN + jurnal.'],
                        'workflow' => 'DRAFT → submit → approval-center → APPROVED → POSTED (ledger IN + jurnal INVENTORY_FUEL vs AP_TRADE).',
                        'expected' => 'Saldo tangki naik dan jurnal pembelian BBM terbentuk; receipt POSTED tidak bisa diubah.',
                        'errors' => ['Belum APPROVED' => 'Posting hanya untuk status APPROVED; submit dan setujui dulu.', 'Sudah diposting' => 'Receipt POSTED immutable; koreksi via reversal jurnal.'],
                        'tips' => ['Harga satuan receipt ikut menentukan avg-cost (rata-rata) tangki untuk issue berikutnya.'],
                        'related' => [['Pusat Approval', '/docs/approval/center'], ['Jurnal', '/docs/finance/journals']],
                        'keywords' => 'bbm receipt penerimaan tangki draft approved posted ledger jurnal approval',
                    ],
                    'issues' => [
                        'title' => 'Pengeluaran BBM (Issue)',
                        'module' => 'BBM → Pengeluaran',
                        'permission' => 'fuel.view',
                        'nav' => 'Armada & BBM → Pengeluaran BBM',
                        'shot' => 'fuel/issues.png',
                        'purpose' => 'Keluarkan BBM ke unit dengan alur DRAFT → submit → pusat approval → APPROVED → POSTED; posting memakai avg-cost tangki, mencatat ledger OUT, LPH, variansi vs standar, dan jurnal beban.',
                        'steps' => ['Buat issue: tangki, unit/plat, liter, HM awal/akhir.', 'Submit lalu setujui di pusat approval.', 'Klik Posting setelah APPROVED.', 'Cek LPH dan variansi vs standar kategori.'],
                        'fields' => ['Unit/Plat' => 'Wajib menunjuk unit atau plat kendaraan.', 'HM' => 'HM akhir tidak boleh lebih kecil dari HM awal.'],
                        'buttons' => ['Submit' => 'Kirim ke approval center.', 'Posting' => 'Catat ledger OUT + jurnal beban.'],
                        'workflow' => 'DRAFT → submit → approval-center → APPROVED → POSTED (ledger OUT + avg-cost + jurnal; koreksi via journal reversal).',
                        'expected' => 'Ledger OUT tercatat, LPH terhitung, dan jurnal beban BBM terbentuk.',
                        'errors' => ['Stok tangki kurang' => 'Kurangi liter atau terima BBM dulu ke tangki itu.', 'HM mundur' => 'Betulkan HM awal/akhir sebelum posting.'],
                        'tips' => ['Biaya issue memakai avg-cost tangki (rata-rata dari baris IN), bukan harga terakhir.'],
                        'related' => [['Pusat Approval', '/docs/approval/center'], ['Buku Besar', '/docs/finance/ledger']],
                        'keywords' => 'bbm issue pengeluaran solar avg-cost ledger lph variansi jurnal posted',
                    ],
                    'dips' => [
                        'title' => 'Dip Tangki & Selisih',
                        'module' => 'BBM → Dip Tangki',
                        'permission' => 'fuel.view',
                        'nav' => 'Armada & BBM → Dip Tangki',
                        'shot' => 'fuel/dips.png',
                        'purpose' => 'Ukur fisik tangki (dip) vs saldo sistem; selisih melewati threshold (setting fuel.dip_threshold_pct) berstatus PENDING dan wajib di-approve.',
                        'steps' => ['Input hasil dip fisik per tangki dan tanggal.', 'Sistem hitung selisih vs saldo ledger.', 'Bila melewati threshold, dip berstatus PENDING.', 'Approve dip PENDING oleh yang berwenang.'],
                        'fields' => ['Variansi %' => 'Selisih fisik vs sistem dibagi saldo sistem.', 'Threshold' => 'Batas wajar dari setting fuel.dip_threshold_pct.'],
                        'buttons' => ['Simpan Dip' => 'Catat hasil ukur fisik.', 'Approve' => 'Setujui dip PENDING (hanya PENDING yang bisa di-approve).'],
                        'workflow' => 'Ukur dip → hitung variansi vs threshold → PENDING → approve.',
                        'expected' => 'Selisih kecil lolos; selisih besar tercatat PENDING sampai di-approve.',
                        'errors' => ['Bukan PENDING' => 'Hanya dip PENDING yang dapat di-approve.'],
                        'tips' => ['Dip melewati threshold memicu alert agar segera investigasi kebocoran atau salah catat.'],
                        'related' => [['Dashboard BBM', '/docs/fuel/dashboard'], ['Penerimaan BBM', '/docs/fuel/receipts']],
                        'keywords' => 'dip tangki selisih threshold pending approve fisik ledger',
                    ],
                ],
            ],
            'tire' => [
                'title' => 'Manajemen Ban',
                'pages' => [
                    'index' => [
                        'title' => 'Overview Ban',
                        'module' => 'Ban → Overview',
                        'permission' => 'tire.view',
                        'nav' => 'Armada & BBM → Overview Ban',
                        'shot' => 'tire/overview.png',
                        'purpose' => 'Pantau seluruh ban: posisi terpasang, kondisi, umur (HM/KM), dan biaya repair yang masuk cost engine.',
                        'steps' => ['Buka Overview Ban.', 'Filter per site, unit, atau kondisi.', 'Klik nomor seri untuk riwayat.', 'Catat movement baru bila ada rotasi/repair.'],
                        'fields' => ['Kondisi' => 'Baru, terpasang, repair, vulkanisir, atau scrap.', 'Posisi' => 'Unit + posisi roda terpasang.'],
                        'buttons' => ['Movement Baru' => 'Catat pasang, lepas, rotasi, repair, atau scrap.'],
                        'workflow' => 'Master ban → movement → overview + biaya repair ke cost engine.',
                        'expected' => 'Setiap ban terlacak posisi dan kondisinya.',
                        'errors' => ['Ban ganda terpasang' => 'Lepas dulu dari unit lama sebelum pasang ke unit baru.'],
                        'tips' => ['Biaya movement REPAIR otomatis masuk komponen repair ban di biaya per ton.'],
                        'related' => [['Detail Ban', '/docs/tire/detail'], ['Biaya per Ton', '/docs/cost/dashboard']],
                        'keywords' => 'ban tire overview vulkanisir repair rotasi serial',
                    ],
                    'detail' => [
                        'title' => 'Detail & Riwayat Ban',
                        'module' => 'Ban → Detail',
                        'permission' => 'tire.view',
                        'nav' => 'Armada & BBM → Detail Ban',
                        'shot' => 'tire/detail.png',
                        'purpose' => 'Riwayat lengkap satu ban: pemasangan, rotasi, repair berbiaya, dan umur pakai sampai scrap.',
                        'steps' => ['Buka Overview lalu klik nomor seri ban.', 'Cek tab riwayat movement.', 'Cek total biaya repair ban.', 'Catat movement penutup bila ban di-scrap.'],
                        'fields' => ['Nomor Seri' => 'Identitas unik tiap ban.', 'Biaya' => 'Akumulasi biaya repair dari movement REPAIR.'],
                        'buttons' => ['Movement Baru' => 'Tambah riwayat ban ini.'],
                        'workflow' => 'Movement per ban → riwayat + akumulasi biaya.',
                        'expected' => 'Umur dan biaya per ban terlihat untuk keputusan vulkanisir vs beli baru.',
                        'errors' => ['Riwayat kosong' => 'Ban belum punya movement; catat pemasangan awal.'],
                        'tips' => ['Bandingkan umur ban antar merek untuk pengadaan berikutnya.'],
                        'related' => [['Overview Ban', '/docs/tire/index'], ['Purchase Order', '/docs/procurement/purchase-orders']],
                        'keywords' => 'ban detail riwayat serial repair scrap umur',
                    ],
                ],
            ],
            'dispatch' => [
                'title' => 'Dispatch & Ritase',
                'pages' => [
                    'board' => [
                        'title' => 'Papan Dispatch',
                        'module' => 'Dispatch → Papan',
                        'permission' => 'dispatch.view',
                        'nav' => 'Operasi → Papan Dispatch',
                        'shot' => 'dispatch/board.png',
                        'purpose' => 'Atur antrean unit per rute dengan fase PLANNED → LOADING → HAULING → DUMPED → COMPLETED; tiap fase dicatat berurutan.',
                        'steps' => ['Buka Papan Dispatch.', 'Buat order dispatch (unit, rute, target rit).', 'Majukan fase: LOADING → HAULING → DUMPED.', 'Selesaikan trip menjadi COMPLETED.'],
                        'fields' => ['Fase' => 'PLANNED, LOADING, HAULING, DUMPED, COMPLETED, CANCELLED.', 'Rute' => 'Asal → tujuan dari master dispatch.'],
                        'buttons' => ['Maju Fase' => 'LOADING/HAULING/DUMPED/COMPLETED berurutan.', 'Batal' => 'Batalkan order PLANNED.'],
                        'workflow' => 'PLANNED → LOADING → HAULING → DUMPED → COMPLETED (fase maju berurutan).',
                        'expected' => 'Posisi tiap unit dan fasenya terpantau real-time di papan.',
                        'errors' => ['Lompat fase' => 'Majukan fase satu per satu sesuai urutan.'],
                        'tips' => ['Gunakan papan per shift agar antrean loading tidak menumpuk.'],
                        'related' => [['Trip Ritase', '/docs/dispatch/trips'], ['Tiket Timbangan', '/docs/weighbridge/tickets']],
                        'keywords' => 'dispatch papan ritase planned loading hauling dumped completed fase',
                    ],
                    'trips' => [
                        'title' => 'Trip / Ritase',
                        'module' => 'Dispatch → Trip',
                        'permission' => 'dispatch.view',
                        'nav' => 'Operasi → Trip Ritase',
                        'shot' => 'dispatch/trips.png',
                        'purpose' => 'Catat tiap rit: unit, rute, dan tonase dari tiket timbangan; tonase trip mengikuti tiket (bukan input manual).',
                        'steps' => ['Buka daftar Trip.', 'Pilih trip dari order dispatch.', 'Tautkan tiket timbangan sebagai sumber tonase.', 'Selesaikan trip setelah tiket tercatat.'],
                        'fields' => ['Tonase' => 'Diambil dari tiket timbangan terkait.', 'Tiket' => 'Nomor tiket jembatan timbang.'],
                        'buttons' => ['Selesaikan' => 'Tandai trip COMPLETED.', 'Lihat Tiket' => 'Lompat ke tiket timbangan.'],
                        'workflow' => 'Dispatch COMPLETED + tiket timbangan → tonase trip final.',
                        'expected' => 'Jumlah rit dan total tonase per unit/rute akurat.',
                        'errors' => ['Tanpa tiket' => 'Trip belum punya tonase valid sampai tiket ditautkan.'],
                        'tips' => ['Selisih rit vs tiket biasanya karena tiket ganda atau trip batal.'],
                        'related' => [['Papan Dispatch', '/docs/dispatch/board'], ['Tiket Timbangan', '/docs/weighbridge/tickets']],
                        'keywords' => 'trip ritase tonase tiket timbangan hauling unit',
                    ],
                    'master' => [
                        'title' => 'Master Rute & Tarif',
                        'module' => 'Dispatch → Master',
                        'permission' => 'dispatch.view',
                        'nav' => 'Operasi → Master Dispatch',
                        'shot' => 'dispatch/master.png',
                        'purpose' => 'Master rute angkut (asal → tujuan, jarak) dan tarif ritase sebagai dasar dispatch dan settlement hauling.',
                        'steps' => ['Buka Master Dispatch.', 'Tambah rute asal → tujuan + jarak.', 'Isi tarif per ton/rit bila berlaku.', 'Aktifkan rute untuk dipakai dispatch.'],
                        'fields' => ['Jarak' => 'Dasar hitung kebutuhan unit dan biaya.', 'Tarif' => 'Dipakai settlement kontrak hauling.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola rute dan tarif.'],
                        'workflow' => 'Master rute → order dispatch → trip → settlement.',
                        'expected' => 'Rute baru langsung bisa dipilih di papan dispatch.',
                        'errors' => ['Rute nonaktif' => 'Aktifkan dulu rute sebelum dipakai order baru.'],
                        'tips' => ['Samakan nama lokasi rute dengan stockpile agar laporan konsisten.'],
                        'related' => [['Papan Dispatch', '/docs/dispatch/board'], ['Settlement Hauling', '/docs/hauling/settlement']],
                        'keywords' => 'master rute tarif dispatch jarak hauling ritase',
                    ],
                ],
            ],
            'hauling' => [
                'title' => 'Hauling & Kontrak Angkut',
                'pages' => [
                    'contracts' => [
                        'title' => 'Kontrak Hauling',
                        'module' => 'Hauling → Kontrak',
                        'permission' => 'contract.view',
                        'nav' => 'Operasi → Kontrak Hauling',
                        'shot' => 'contract/hauling.png',
                        'purpose' => 'Kontrak jasa angkut dengan kontraktor: rute, tarif per ton, kuota tonase, dan periode berlaku.',
                        'steps' => ['Buka Kontrak Hauling.', 'Buat kontrak: kontraktor, rute, tarif, kuota.', 'Aktifkan kontrak periode berjalan.', 'Pantau realisasi kuota per kontrak.'],
                        'fields' => ['Kuota' => 'Batas tonase kontrak periode ini.', 'Tarif' => 'Rupiah per ton per rute.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola kontrak hauling.'],
                        'workflow' => 'Kontrak hauling → trip dispatch → settlement per periode.',
                        'expected' => 'Kontrak aktif membatasi dan menilai jasa angkut kontraktor.',
                        'errors' => ['Over-kuota' => 'Kelebihan tonase diblokir; butuh izin contract.override atau approval khusus.'],
                        'tips' => ['Pisahkan kontrak per kontraktor dan rute agar settlement tidak tercampur.'],
                        'related' => [['Settlement Hauling', '/docs/hauling/settlement'], ['Realisasi Kontrak', '/docs/contract/realization']],
                        'keywords' => 'hauling kontrak angkut kontraktor tarif kuota tonase',
                    ],
                    'settlement' => [
                        'title' => 'Settlement Hauling',
                        'module' => 'Hauling → Settlement',
                        'permission' => 'contract.view',
                        'nav' => 'Operasi → Settlement Hauling',
                        'shot' => 'contract/hauling-settlement.png',
                        'purpose' => 'Hitung tagihan jasa angkut per periode dari trip COMPLETED × tarif kontrak; selisih kuota diselesaikan via approval khusus.',
                        'steps' => ['Buka Settlement Hauling.', 'Pilih kontraktor dan periode.', 'Tarik trip COMPLETED periode itu.', 'Kunci settlement untuk penagihan.'],
                        'fields' => ['Trip Dihitung' => 'Hanya trip COMPLETED bertiket valid.', 'Nilai' => 'Total ton × tarif kontrak rute.'],
                        'buttons' => ['Tarik Trip' => 'Hitung settlement periode.', 'Kunci' => 'Finalisasi untuk ditagih.'],
                        'workflow' => 'Trip COMPLETED → tarif kontrak → settlement → tagihan.',
                        'expected' => 'Nilai settlement sama dengan rekap trip × tarif.',
                        'errors' => ['Trip belum lengkap' => 'Selesaikan trip dan tautkan tiket dulu sebelum ditarik.'],
                        'tips' => ['Kunci settlement sebelum tutup periode fiskal agar angka tidak berubah.'],
                        'related' => [['Kontrak Hauling', '/docs/hauling/contracts'], ['Laporan Mining', '/docs/reports/mining']],
                        'keywords' => 'settlement hauling tagihan trip tarif kontraktor periode',
                    ],
                ],
            ],
            'stockpile' => [
                'title' => 'Stockpile',
                'pages' => [
                    'board' => [
                        'title' => 'Papan Stockpile',
                        'module' => 'Stockpile → Papan',
                        'permission' => 'stockpile.view',
                        'nav' => 'Operasi → Papan Stockpile',
                        'shot' => 'stockpile/board.png',
                        'purpose' => 'Pantau saldo tiap ROM/port stockpile dari batch produksi POSTED; survei dengan selisih besar berstatus INVESTIGATE + alert.',
                        'steps' => ['Buka Papan Stockpile.', 'Cek saldo sistem per lokasi.', 'Input hasil survei fisik bila ada opname.', 'Investigasi survei berstatus INVESTIGATE.'],
                        'fields' => ['Saldo Sistem' => 'Dari batch produksi POSTED masuk/keluar.', 'Status Survei' => 'PENDING wajar atau INVESTIGATE bila selisih > threshold.'],
                        'buttons' => ['Input Survei' => 'Catat hasil ukur fisik.', 'Investigasi' => 'Isi hasil investigasi selisih.'],
                        'workflow' => 'Batch POSTED → saldo → survei → INVESTIGATE + alert bila selisih > threshold.',
                        'expected' => 'Saldo per stockpile dan survei bermasalah terlihat jelas.',
                        'errors' => ['Selisih besar' => 'Survei otomatis INVESTIGATE; wajib diisi investigasi sebelum approve.'],
                        'tips' => ['Opname rutin tiap akhir shift menekan selisih tidak tercatat.'],
                        'related' => [['Detail Stockpile', '/docs/stockpile/detail'], ['Batch Produksi', '/docs/production/batches']],
                        'keywords' => 'stockpile rom saldo survei investigate opname papan',
                    ],
                    'detail' => [
                        'title' => 'Detail Stockpile & Survei',
                        'module' => 'Stockpile → Detail',
                        'permission' => 'stockpile.view',
                        'nav' => 'Operasi → Detail Stockpile',
                        'shot' => 'stockpile/detail.png',
                        'purpose' => 'Rincian mutasi satu stockpile dan approval survei: engine menyetujui lalu rebase saldo sistem ke hasil survei yang sah.',
                        'steps' => ['Pilih lokasi dari papan stockpile.', 'Cek mutasi masuk/keluar periode.', 'Review survei INVESTIGATE + investigasinya.', 'Approve via engine untuk rebase saldo.'],
                        'fields' => ['Rebase' => 'Saldo sistem disetel ulang ke hasil survei approved.', 'Investigasi' => 'Wajib diisi untuk survei INVESTIGATE.'],
                        'buttons' => ['Approve Survei' => 'Setujui via engine + rebase.', 'Riwayat' => 'Lihat survei terdahulu.'],
                        'workflow' => 'Survei INVESTIGATE → investigasi → engine approval → rebase saldo.',
                        'expected' => 'Setelah approve, saldo sistem sama dengan survei sah + tercatat di audit.',
                        'errors' => ['Tanpa investigasi' => 'Survei INVESTIGATE tanpa investigasi tidak bisa di-approve.'],
                        'tips' => ['Rebase hanya untuk survei sah; salah catat harian betulkan via batch, bukan survei.'],
                        'related' => [['Papan Stockpile', '/docs/stockpile/board'], ['Saldo Stok', '/docs/inventory/stock-balance']],
                        'keywords' => 'stockpile detail survei investigate approve rebase mutasi',
                    ],
                ],
            ],
            'quality' => [
                'title' => 'Quality Control & Lab',
                'pages' => [
                    'samples' => [
                        'title' => 'Sampel & Hasil Uji',
                        'module' => 'QC → Sampel',
                        'permission' => 'quality.view',
                        'nav' => 'Operasi → Sampel QC',
                        'shot' => 'quality/samples.png',
                        'purpose' => 'Catat sampel dan hasil uji lab; sistem menilai PASS/FAIL otomatis vs spec dan sampel FAIL langsung membuat HOLD.',
                        'steps' => ['Buat sampel dari lot/batch produksi.', 'Input hasil uji per parameter.', 'Sistem menilai PASS/FAIL vs spec.', 'Tindak lanjuti FAIL yang otomatis HOLD.'],
                        'fields' => ['Parameter' => 'Mis. kalori, sulfur, ash, moisture vs batas spec.', 'Verdict' => 'PASS bila semua parameter dalam spec, FAIL bila ada yang lewat.'],
                        'buttons' => ['Input Hasil' => 'Catat hasil uji lab.', 'Lihat HOLD' => 'Lompat ke hold yang terbentuk.'],
                        'workflow' => 'Sampel → hasil uji → PASS/FAIL otomatis → FAIL auto-HOLD.',
                        'expected' => 'Setiap lot punya verdict jelas; FAIL langsung diblokir.',
                        'errors' => ['Spec belum ada' => 'Buat spec dulu agar verdict bisa dinilai otomatis.'],
                        'tips' => ['Input hasil segera setelah lab keluar agar DO tidak telanjur jalan.'],
                        'related' => [['Spesifikasi', '/docs/quality/specs'], ['Hold Kualitas', '/docs/quality/holds']],
                        'keywords' => 'qc sampel lab hasil uji pass fail spec hold',
                    ],
                    'specs' => [
                        'title' => 'Spesifikasi (Spec)',
                        'module' => 'QC → Spesifikasi',
                        'permission' => 'quality.view',
                        'nav' => 'Operasi → Spesifikasi QC',
                        'shot' => 'quality/specs.png',
                        'purpose' => 'Batas kualitas per produk/pembeli (kalori, sulfur, ash, moisture) sebagai acuan verdict PASS/FAIL otomatis.',
                        'steps' => ['Buka Spesifikasi.', 'Tambah spec per produk/pembeli.', 'Isi batas min/maks tiap parameter.', 'Aktifkan spec periode berlaku.'],
                        'fields' => ['Batas' => 'Min/maks tiap parameter uji.', 'Berlaku' => 'Spec aktif dipakai penilaian otomatis.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola spec kualitas.'],
                        'workflow' => 'Spec aktif → acuan verdict sampel otomatis.',
                        'expected' => 'Sampel baru langsung dinilai terhadap spec aktif.',
                        'errors' => ['Spec ganda aktif' => 'Nonaktifkan spec lama sebelum mengaktifkan revisi.'],
                        'tips' => ['Samakan parameter spec dengan klausul kontrak pelanggan.'],
                        'related' => [['Sampel QC', '/docs/quality/samples'], ['Kontrak Pelanggan', '/docs/contract/customers']],
                        'keywords' => 'spec spesifikasi batas kalori sulfur ash moisture pass fail',
                    ],
                    'holds' => [
                        'title' => 'Hold / Blokir Kualitas',
                        'module' => 'QC → Hold',
                        'permission' => 'quality.view',
                        'nav' => 'Operasi → Hold Kualitas',
                        'shot' => 'quality/holds.png',
                        'purpose' => 'HOLD aktif memblokir penyelesaian delivery order; pelepasan hanya via release atau pengiriman khusus yang disetujui di pusat approval, dan CoA hanya terbit untuk sampel PASS.',
                        'steps' => ['Buka daftar HOLD dari sampel FAIL.', 'Cek lot dan parameter gagal.', 'Ajukan pengiriman khusus via pusat approval bila mendesak.', 'Release HOLD setelah masalah selesai; CoA hanya untuk PASS.'],
                        'fields' => ['Status HOLD' => 'Aktif memblokir DO sampai release/approval khusus.', 'CoA' => 'Certificate of Analysis hanya untuk sampel PASS tanpa hasil belum PASS.'],
                        'buttons' => ['Release' => 'Lepas blokir setelah lolos.', 'Approval Khusus' => 'Via /docs/approval/center.'],
                        'workflow' => 'FAIL → HOLD → blokir delivery → release / approval-khusus; CoA hanya untuk PASS.',
                        'expected' => 'DO lot HOLD tidak bisa selesai; lot PASS bisa terbit CoA.',
                        'errors' => ['DO diblokir HOLD' => 'Release HOLD atau ajukan pengiriman khusus via approval center.', 'CoA ditolak' => 'Masih ada hasil belum PASS pada sampel itu.'],
                        'tips' => ['Jangan release HOLD tanpa uji ulang yang PASS.'],
                        'related' => [['Sampel QC', '/docs/quality/samples'], ['Delivery Order', '/docs/sales/delivery-orders']],
                        'keywords' => 'hold blokir fail delivery coa pass approval khusus release',
                    ],
                ],
            ],
            'cost' => [
                'title' => 'Biaya per Ton',
                'pages' => [
                    'dashboard' => [
                        'title' => 'Dashboard Biaya per Ton',
                        'module' => 'Biaya → Dashboard',
                        'permission' => 'cost.view',
                        'nav' => 'Keuangan → Biaya per Ton',
                        'shot' => 'cost/dashboard.png',
                        'purpose' => 'Cost engine menghitung biaya per ton live dari transaksi nyata: BBM POSTED, maintenance + sparepart, repair ban, penyusutan alat, biaya manual, dan tenaga kerja alokasi produksi.',
                        'steps' => ['Buka Dashboard Biaya per Ton.', 'Pilih perusahaan, site, dan periode.', 'Cek komponen: BBM, maintenance, ban, susut, manual, labor.', 'Klik komponen untuk rincian transaksi.'],
                        'fields' => ['Komponen' => 'fuel, maintenance, tire_repair, depreciation, manual (kontraktor/royalti/overhead/hauling/crusher), labor.', 'Denominator' => 'Ton produksi saleable POSTED periode itu.'],
                        'buttons' => ['Filter' => 'Terapkan site/periode.', 'Rincian' => 'Lihat transaksi pembentuk komponen.'],
                        'workflow' => 'Transaksi POSTED → cost engine agregat → biaya per ton.',
                        'expected' => 'Total dan per-ton per komponen sesuai transaksi POSTED.',
                        'errors' => ['Ton nol' => 'Tanpa produksi POSTED, biaya per ton tidak bisa dihitung.'],
                        'tips' => ['Labor dialokasi proporsional produksi antar site; insentif operator termasuk di dalamnya.'],
                        'related' => [['Biaya Manual', '/docs/cost/manual'], ['Laporan Mining', '/docs/reports/mining']],
                        'keywords' => 'biaya per ton cost engine bbm maintenance depresiasi labor royalti',
                    ],
                    'manual' => [
                        'title' => 'Biaya Manual (Other Cost)',
                        'module' => 'Biaya → Manual',
                        'permission' => 'cost.view',
                        'nav' => 'Keuangan → Biaya Manual',
                        'shot' => 'cost/manual.png',
                        'purpose' => 'Catat biaya non-otomatis (kontraktor, royalti, overhead, hauling, crusher, lainnya) per periode; yang POSTED masuk cost engine dan membentuk jurnal.',
                        'steps' => ['Klik Tambah biaya manual.', 'Pilih komponen, periode, site, dan nominal.', 'Submit dan setujui sesuai alur.', 'Posting agar masuk cost engine + jurnal.'],
                        'fields' => ['Komponen' => 'CONTRACTOR, ROYALTY, OVERHEAD, HAULING, CRUSHER, OTHER.', 'Periode' => 'Bulan YYYY-MM biaya dibebankan.'],
                        'buttons' => ['Posting' => 'Masuk cost engine + jurnal beban.', 'Reverse' => 'Koreksi via journal reversal beralasan.'],
                        'workflow' => 'DRAFT → APPROVED → POSTED (masuk cost engine + jurnal; koreksi via journal reversal).',
                        'expected' => 'Nominal POSTED menambah komponen manual di dashboard biaya.',
                        'errors' => ['Periode fiskal tutup' => 'Posting ke periode OPEN; reopen butuh izin fiscal.reopen + alasan + audit.', 'Salah komponen' => 'Reverse lalu buat ulang dengan komponen benar.'],
                        'tips' => ['Kunci periode fiskal setelah settlement agar biaya tidak berubah.'],
                        'related' => [['Dashboard Biaya', '/docs/cost/dashboard'], ['Jurnal', '/docs/finance/journals']],
                        'keywords' => 'biaya manual other cost kontraktor royalti overhead posting reversal',
                    ],
                ],
            ],
            'contract' => [
                'title' => 'Manajemen Kontrak',
                'pages' => [
                    'customers' => [
                        'title' => 'Kontrak Pelanggan',
                        'module' => 'Kontrak → Pelanggan',
                        'permission' => 'contract.view',
                        'nav' => 'Penjualan → Kontrak Pelanggan',
                        'shot' => 'contract/customers.png',
                        'purpose' => 'Kontrak jual ke pembeli: volume, harga, spec kualitas, dan periode; realisasi ditarik dari faktur/DO.',
                        'steps' => ['Buka Kontrak Pelanggan.', 'Buat kontrak: pembeli, volume, harga, spec.', 'Aktifkan kontrak periode berjalan.', 'Pantau realisasi vs kuota.'],
                        'fields' => ['Volume' => 'Kuota tonase kontrak.', 'Harga/Spec' => 'Dasar faktur dan uji QC.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola kontrak pelanggan.'],
                        'workflow' => 'Kontrak → DO/faktur → realisasi kuota.',
                        'expected' => 'Realisasi terkumpul otomatis dari dokumen penjualan.',
                        'errors' => ['Over-contract' => 'Kelebihan kuota diblokir; butuh izin contract.override atau approval khusus.'],
                        'tips' => ['Tautkan spec QC ke klausul kontrak agar FAIL otomatis menahan kiriman.'],
                        'related' => [['Realisasi Kontrak', '/docs/contract/realization'], ['Faktur Penjualan', '/docs/sales/invoices']],
                        'keywords' => 'kontrak pelanggan volume harga realisasi kuota over-contract',
                    ],
                    'suppliers' => [
                        'title' => 'Kontrak Supplier',
                        'module' => 'Kontrak → Supplier',
                        'permission' => 'contract.view',
                        'nav' => 'Pembelian → Kontrak Supplier',
                        'shot' => 'contract/suppliers.png',
                        'purpose' => 'Kontrak beli dari supplier: item, harga, dan kuota; realisasi ditarik dari PO/GRN.',
                        'steps' => ['Buka Kontrak Supplier.', 'Buat kontrak: supplier, item, harga, kuota.', 'Aktifkan kontrak periode berjalan.', 'Pantau realisasi penerimaan.'],
                        'fields' => ['Kuota' => 'Batas qty/nilai kontrak.', 'Harga' => 'Acuan PO.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola kontrak supplier.'],
                        'workflow' => 'Kontrak → PO → GRN → realisasi.',
                        'expected' => 'Sisa kuota berkurang setiap penerimaan tercatat.',
                        'errors' => ['Over-contract' => 'Melebihi sisa diblokir; butuh izin contract.override.'],
                        'tips' => ['Buat kontrak terpisah per item utama agar sisa mudah dipantau.'],
                        'related' => [['Realisasi Kontrak', '/docs/contract/realization'], ['Purchase Order', '/docs/procurement/purchase-orders']],
                        'keywords' => 'kontrak supplier kuota po grn realisasi over-contract',
                    ],
                    'realization' => [
                        'title' => 'Realisasi Kontrak',
                        'module' => 'Kontrak → Realisasi',
                        'permission' => 'contract.view',
                        'nav' => 'Kontrak → Realisasi',
                        'shot' => 'reports/contract.png',
                        'purpose' => 'Rekap realisasi vs kuota semua kontrak; transaksi over-contract diblokir kecuali pemegang izin contract.override atau approval khusus.',
                        'steps' => ['Buka Realisasi Kontrak.', 'Filter jenis kontrak dan periode.', 'Cek % realisasi dan sisa kuota.', 'Ajukan override bila over-contract mendesak.'],
                        'fields' => ['Realisasi %' => 'Realisasi dibagi kuota kontrak.', 'Override' => 'Bypass via izin contract.override + audit.'],
                        'buttons' => ['Filter' => 'Terapkan jenis/periode.', 'Ajukan Override' => 'Via pusat approval.'],
                        'workflow' => 'Dokumen (DO/faktur/PO) → cek sisa → blokir bila over-contract tanpa contract.override.',
                        'expected' => 'Sisa kuota dan status over-contract akurat per kontrak.',
                        'errors' => ['Over-contract diblokir' => 'Minta approval khusus atau user berizin contract.override.'],
                        'tips' => ['Cek realisasi sebelum buat DO/PO baru agar tidak tertolak.'],
                        'related' => [['Kontrak Pelanggan', '/docs/contract/customers'], ['Pusat Approval', '/docs/approval/center']],
                        'keywords' => 'realisasi kontrak kuota sisa over-contract override approval',
                    ],
                ],
            ],
            'budget' => [
                'title' => 'Budgeting',
                'pages' => [
                    'index' => [
                        'title' => 'Daftar Budget',
                        'module' => 'Budget → Daftar',
                        'permission' => 'budget.view',
                        'nav' => 'Keuangan → Daftar Budget',
                        'shot' => 'budget/index.png',
                        'purpose' => 'Daftar pagu anggaran per akun/departemen/site; setiap pakai dana melewati cek → commit → consume/release.',
                        'steps' => ['Buka Daftar Budget.', 'Filter tahun dan site.', 'Klik baris untuk detail dan sisa.', 'Buat budget baru bila perlu.'],
                        'fields' => ['Pagu' => 'Batas anggaran periode.', 'Sisa' => 'Pagu − commit − consume.'],
                        'buttons' => ['Detail' => 'Buka rincian budget.', 'Tambah' => 'Buat pagu baru.'],
                        'workflow' => 'Buat pagu → cek/commit saat dokumen → consume saat realisasi.',
                        'expected' => 'Pagu dan sisa per akun selalu terkini.',
                        'errors' => ['Pagu terlampaui' => 'Mode block menolak; mode warning hanya memberi peringatan (setting budget.enforce).'],
                        'tips' => ['Mode penegakan diatur di setting budget.enforce: off, warning, atau block.'],
                        'related' => [['Detail Budget', '/docs/budget/detail'], ['Budget vs Aktual', '/docs/budget/vs-actual']],
                        'keywords' => 'budget anggaran pagu sisa commit consume enforce',
                    ],
                    'detail' => [
                        'title' => 'Detail Budget',
                        'module' => 'Budget → Detail',
                        'permission' => 'budget.view',
                        'nav' => 'Keuangan → Detail Budget',
                        'shot' => 'budget/detail.png',
                        'purpose' => 'Rincian satu budget: pagu, commit (dicadangkan dokumen), consume (terpakai), release (cadangan dilepas); dokumen fiskal mengikuti periode tutup/buka dengan alasan + audit.',
                        'steps' => ['Buka detail dari daftar budget.', 'Cek commit, consume, dan sisa.', 'Release commit yang batal.', 'Posting hanya ke periode fiskal OPEN.'],
                        'fields' => ['Commit' => 'Dana dicadangkan dokumen belum realisasi.', 'Consume/Release' => 'Terpakai vs cadangan dilepas kembali.'],
                        'buttons' => ['Release' => 'Lepas commit yang batal.', 'Riwayat' => 'Lihat mutasi budget.'],
                        'workflow' => 'check → commit → consume/release; fiscal close/reopen butuh alasan + audit.',
                        'expected' => 'Sisa = pagu − commit − consume secara konsisten.',
                        'errors' => ['Periode ditutup' => 'Pakai periode OPEN; reopen butuh izin fiscal.reopen + alasan + audit.'],
                        'tips' => ['Release commit batal agar sisa tidak tertahan.'],
                        'related' => [['Daftar Budget', '/docs/budget/index'], ['Jurnal', '/docs/finance/journals']],
                        'keywords' => 'budget detail commit consume release fiscal close reopen audit',
                    ],
                    'vs-actual' => [
                        'title' => 'Budget vs Aktual',
                        'module' => 'Budget → Vs Aktual',
                        'permission' => 'budget.view',
                        'nav' => 'Keuangan → Budget vs Aktual',
                        'shot' => 'reports/budget.png',
                        'purpose' => 'Bandingkan pagu vs realisasi jurnal POSTED; mode block menolak dokumen over-budget, mode warning meloloskan dengan peringatan (setting budget.enforce).',
                        'steps' => ['Buka Budget vs Aktual.', 'Pilih periode dan site.', 'Cek variansi pagu vs aktual.', 'Tindak lanjuti akun over-budget.'],
                        'fields' => ['Variansi' => 'Aktual − pagu; minus berarti hemat.', 'Mode' => 'block vs warning dari setting budget.enforce.'],
                        'buttons' => ['Filter' => 'Terapkan periode/site.', 'Cetak' => 'Cetak laporan.'],
                        'workflow' => 'Jurnal POSTED → aktual → banding vs pagu.',
                        'expected' => 'Akun over-budget tertandai sesuai mode penegakan.',
                        'errors' => ['Ditolak over-budget' => 'Mode block: tambah pagu atau revisi dokumen; mode warning cukup catat alasan.'],
                        'tips' => ['Review vs-aktual sebelum tutup periode fiskal.'],
                        'related' => [['Daftar Budget', '/docs/budget/index'], ['Buku Besar', '/docs/finance/ledger']],
                        'keywords' => 'budget vs aktual variansi block warning enforce over-budget',
                    ],
                ],
            ],
            'hse' => [
                'title' => 'HSE / K3',
                'pages' => [
                    'dashboard' => [
                        'title' => 'Dashboard HSE',
                        'module' => 'HSE → Dashboard',
                        'permission' => 'hse.view',
                        'nav' => 'HSE → Dashboard',
                        'shot' => 'hse/dashboard.png',
                        'purpose' => 'Ringkasan insiden per severity, status tindak lanjut, dan permit yang akan kedaluwarsa (expiry alerts).',
                        'steps' => ['Buka Dashboard HSE.', 'Cek insiden open per severity.', 'Cek permit mendekati kedaluwarsa.', 'Klik untuk tindak lanjut laporan.'],
                        'fields' => ['Severity' => 'Ringan, sedang, berat, fatal.', 'Expiry Alert' => 'Permit APPROVED/ACTIVE yang hampir habis.'],
                        'buttons' => ['Lapor Insiden' => 'Buat laporan baru.', 'Lihat Permit' => 'Lompat ke daftar permit.'],
                        'workflow' => 'Laporan → investigasi → action → verify → engine close; permit expiry alerts.',
                        'expected' => 'Insiden open dan permit kritis terpantau satu layar.',
                        'errors' => ['Data tidak sinkron' => 'Pastikan laporan dan aksi sudah di-verify sebelum close.'],
                        'tips' => ['Prioritaskan severity berat/fatal setiap pagi.'],
                        'related' => [['Laporan Insiden', '/docs/hse/reports'], ['Permit HSE', '/docs/hse/permits']],
                        'keywords' => 'hse dashboard k3 insiden severity permit expiry alert',
                    ],
                    'reports' => [
                        'title' => 'Laporan Insiden',
                        'module' => 'HSE → Laporan',
                        'permission' => 'hse.view',
                        'nav' => 'HSE → Laporan Insiden',
                        'shot' => 'hse/reports.png',
                        'purpose' => 'Alur laporan insiden: report → investigate (root cause) → action (owner + due date) → evidence → verify → engine close.',
                        'steps' => ['Buat laporan: lokasi, waktu, kronologi, severity.', 'Investigasi dan isi root cause.', 'Buat action dengan owner + due date.', 'Upload evidence, verify, lalu engine close.'],
                        'fields' => ['Root Cause' => 'Hasil investigasi wajib sebelum action.', 'Owner+Due' => 'Penanggung jawab dan tenggat tiap action.'],
                        'buttons' => ['Investigasi' => 'Catat root cause.', 'Verify' => 'Verifikasi evidence action.', 'Close' => 'Tutup via engine.'],
                        'workflow' => 'report → investigate → action(owner+due) → evidence → verify → engine close.',
                        'expected' => 'Laporan tertutup hanya setelah semua action ter-verify.',
                        'errors' => ['Belum bisa close' => 'Masih ada action belum verify atau evidence kurang.'],
                        'tips' => ['Lampirkan foto evidence agar verifikasi cepat lolos.'],
                        'related' => [['Dashboard HSE', '/docs/hse/dashboard'], ['Pusat Approval', '/docs/approval/center']],
                        'keywords' => 'hse insiden laporan investigasi action evidence verify close',
                    ],
                    'permits' => [
                        'title' => 'Izin / Permit HSE',
                        'module' => 'HSE → Permit',
                        'permission' => 'hse.view',
                        'nav' => 'HSE → Permit',
                        'shot' => 'hse/permits.png',
                        'purpose' => 'Kelola permit kerja (hot work, confined space, ketinggian); status APPROVED/ACTIVE yang mendekati habis memicu expiry alert.',
                        'steps' => ['Buka daftar Permit.', 'Buat permit: jenis, lokasi, periode berlaku.', 'Ajukan approval permit.', 'Perpanjang sebelum kedaluwarsa.'],
                        'fields' => ['Berlaku' => 'Tanggal mulai–selesai izin kerja.', 'Status' => 'DRAFT, APPROVED, ACTIVE, atau expired.'],
                        'buttons' => ['Perpanjang' => 'Buat permit pengganti.', 'Cek Expiry' => 'Lihat alert kedaluwarsa.'],
                        'workflow' => 'Pengajuan → APPROVED/ACTIVE → expiry alert → perpanjang.',
                        'expected' => 'Tidak ada pekerjaan berisiko berjalan dengan permit kedaluwarsa.',
                        'errors' => ['Permit kedaluwarsa' => 'Hentikan pekerjaan dan terbitkan permit baru.'],
                        'tips' => ['Cek expiry alert mingguan untuk semua permit ACTIVE.'],
                        'related' => [['Dashboard HSE', '/docs/hse/dashboard'], ['Register Compliance', '/docs/compliance/register']],
                        'keywords' => 'permit izin hse expiry approved active perpanjang k3',
                    ],
                ],
            ],
            'compliance' => [
                'title' => 'Compliance',
                'pages' => [
                    'register' => [
                        'title' => 'Register Compliance',
                        'module' => 'Compliance → Register',
                        'permission' => 'compliance.view',
                        'nav' => 'Umum → Register Compliance',
                        'shot' => 'compliance/register.png',
                        'purpose' => 'Register kewajiban/izin perusahaan dengan tanggal jatuh tempo; sistem mengirim reminder H-90/60/30/14/7 dan saat expired.',
                        'steps' => ['Buka Register Compliance.', 'Tambah kewajiban: jenis, nomor, expiry.', 'Pantau status reminder.', 'Perpanjang (renew) sebelum expired.'],
                        'fields' => ['Expiry' => 'Tanggal habis berlaku dokumen.', 'Reminder' => 'Otomatis H-90/60/30/14/7 + expired.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola register.', 'Renew' => 'Perpanjang dokumen.'],
                        'workflow' => 'Daftarkan expiry → reminder H-90/60/30/14/7 → renew.',
                        'expected' => 'Tidak ada izin terlewat; pengingat terkirim bertahap.',
                        'errors' => ['Sudah expired' => 'Segera renew dan catat nomor dokumen baru.'],
                        'tips' => ['Lampirkan file dokumen agar audit mudah.'],
                        'related' => [['Kalender Kepatuhan', '/docs/compliance/calendar'], ['Permit HSE', '/docs/hse/permits']],
                        'keywords' => 'compliance register reminder expiry renew h-90 izin',
                    ],
                    'calendar' => [
                        'title' => 'Kalender Kepatuhan',
                        'module' => 'Compliance → Kalender',
                        'permission' => 'compliance.view',
                        'nav' => 'Umum → Kalender Kepatuhan',
                        'shot' => 'compliance/calendar.png',
                        'purpose' => 'Tampilan kalender seluruh jatuh tempo compliance agar reminder H-90/60/30/14/7 bisa direncanakan dan di-renew tepat waktu.',
                        'steps' => ['Buka Kalender Kepatuhan.', 'Navigasi bulan jatuh tempo.', 'Klik item untuk detail dokumen.', 'Renew dari register terkait.'],
                        'fields' => ['Warna Status' => 'Dekat/lewat tempo ditandai jelas.', 'Item' => 'Tautan ke register asal.'],
                        'buttons' => ['Detail' => 'Buka register dokumen.', 'Filter' => 'Saring jenis kewajiban.'],
                        'workflow' => 'Register expiry → kalender → reminder → renew.',
                        'expected' => 'Semua deadline 90 hari ke depan terlihat terjadwal.',
                        'errors' => ['Item tidak muncul' => 'Pastikan tanggal expiry di register sudah terisi.'],
                        'tips' => ['Review kalender tiap awal bulan untuk rencana renew.'],
                        'related' => [['Register Compliance', '/docs/compliance/register'], ['Pusat Approval', '/docs/approval/center']],
                        'keywords' => 'kalender compliance jatuh tempo reminder renew schedule',
                    ],
                ],
            ],
            'telematics' => [
                'title' => 'Telematics',
                'pages' => [
                    'overview' => [
                        'title' => 'Overview Telematics',
                        'module' => 'Telematics → Overview',
                        'permission' => 'telematics.view',
                        'nav' => 'Armada → Telematics',
                        'shot' => 'telematics/overview.png',
                        'purpose' => 'Integrasi GPS/IoT unit via driver SIMULATOR (tanpa hardware) atau REST_API (pull); event dinormalisasi ke format yang sama.',
                        'steps' => ['Buka Overview Telematics.', 'Pilih driver: SIMULATOR atau REST_API.', 'Cek event terakhir per unit.', 'Tautkan unit ke data fleet.'],
                        'fields' => ['Driver' => 'SIMULATOR tanpa hardware; REST_API pull dari vendor.', 'Event' => 'Posisi, speed, engine, bahan bakar dinormalisasi.'],
                        'buttons' => ['Uji Koneksi' => 'Cek driver aktif.', 'Lihat Event' => 'Rincian event per unit.'],
                        'workflow' => 'Driver SIMULATOR/REST_API → normalized events → peta + laporan.',
                        'expected' => 'Event tiap unit mengalir dengan format seragam per driver.',
                        'errors' => ['Event kosong' => 'Cek konfigurasi driver dan kredensial REST_API.'],
                        'tips' => ['Pakai SIMULATOR untuk demo dan uji tanpa perangkat.'],
                        'related' => [['Dashboard Armada', '/docs/fleet/dashboard'], ['Perangkat Timbangan', '/docs/iot-weighbridge/devices']],
                        'keywords' => 'telematics gps iot simulator rest_api event tracking unit',
                    ],
                ],
            ],
            'iot-weighbridge' => [
                'title' => 'IoT Timbangan',
                'pages' => [
                    'devices' => [
                        'title' => 'Perangkat Timbangan',
                        'module' => 'IoT → Perangkat',
                        'permission' => 'weighbridge.view',
                        'nav' => 'Timbangan → Perangkat IoT',
                        'shot' => 'iot/devices.png',
                        'purpose' => 'Master perangkat jembatan timbang dengan driver MANUAL (keyboard operator), SERIAL/TCP (daemon polling), atau REST (device push).',
                        'steps' => ['Buka Perangkat Timbangan.', 'Tambah device: nama, lokasi, driver.', 'Isi api_token untuk driver REST.', 'Aktifkan device untuk dipakai tiket.'],
                        'fields' => ['Driver' => 'MANUAL, SERIAL, TCP, atau REST.', 'API Token' => 'Token unik per device untuk push REST.'],
                        'buttons' => ['Tambah/Edit' => 'Kelola device.', 'Uji' => 'Cek koneksi device.'],
                        'workflow' => 'Master device → pembacaan via driver → tiket timbangan.',
                        'expected' => 'Device aktif siap dipakai input tiket.',
                        'errors' => ['Device offline' => 'Cek daemon SERIAL/TCP atau token REST device.'],
                        'tips' => ['Satu lokasi satu device aktif agar tiket tidak tertukar.'],
                        'related' => [['API Timbangan', '/docs/iot-weighbridge/api'], ['Tiket Timbangan', '/docs/weighbridge/tickets']],
                        'keywords' => 'iot weighbridge device manual serial tcp rest token timbangan',
                    ],
                    'api' => [
                        'title' => 'API Pembacaan Timbangan',
                        'module' => 'IoT → API',
                        'permission' => 'weighbridge.view',
                        'nav' => 'Timbangan → API Pembacaan',
                        'shot' => 'iot/api.png',
                        'purpose' => 'Endpoint POST /api/weighbridge/reading untuk push berat dari device REST memakai device token; hasil push menjadi tiket timbangan.',
                        'steps' => ['Salin URL POST /api/weighbridge/reading.', 'Pasang device token di header/request.', 'Kirim berat + nomor kendaraan dari device.', 'Cek tiket yang terbentuk di weighbridge.'],
                        'fields' => ['Token' => 'api_token unik per device, wajib valid.', 'Payload' => 'Berat, waktu, dan identitas kendaraan.'],
                        'buttons' => ['Dokumentasi' => 'Lihat format payload.', 'Lihat Tiket' => 'Lompat ke tiket terbentuk.'],
                        'workflow' => 'POST /api/weighbridge/reading + device token → tiket timbangan.',
                        'expected' => 'Setiap push valid membentuk/memperbarui tiket.',
                        'errors' => ['Token invalid' => 'Gunakan api_token device yang aktif.', 'Payload ditolak' => 'Lengkapi berat dan identitas kendaraan.'],
                        'tips' => ['Rotasi token bila perangkat berpindah tangan.'],
                        'related' => [['Perangkat Timbangan', '/docs/iot-weighbridge/devices'], ['Tiket Timbangan', '/docs/weighbridge/tickets']],
                        'keywords' => 'api weighbridge reading post token rest device payload tiket',
                    ],
                ],
            ],
        ];
    }
}
