@extends('layouts.app')
@section('title', ' - Approval Workflow')
@section('content')
<div class="page-frame" x-data="{ open: false }">
    <div class="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-6"><div><div class="section-kicker">Risk & governance</div><h1 class="text-[28px] font-bold tracking-[-.03em] text-slate-900">Approval Workflow</h1><p class="mt-1 text-sm text-slate-500">Atur ambang nominal, urutan approver, dan scope tanpa hardcode di modul transaksi.</p></div><button @click="open=!open" class="inline-flex items-center justify-center gap-2 h-10 px-4 rounded-lg bg-slate-900 text-white text-sm font-semibold"><x-ui.icon name="plus" class="w-4 h-4" /> Tambah Workflow</button></div>
    <div class="grid xl:grid-cols-[1fr_22rem] gap-5 items-start">
        <section class="dashboard-card overflow-hidden"><header class="px-5 py-4 border-b border-slate-100"><h2 class="font-semibold text-slate-900">Workflow aktif</h2><p class="text-xs text-slate-400 mt-1">{{ $workflows->count() }} konfigurasi terdaftar</p></header><div class="divide-y divide-slate-100">@forelse($workflows as $workflow)<article class="p-5"><div class="flex flex-col sm:flex-row sm:items-start justify-between gap-3"><div><div class="flex items-center gap-2"><h3 class="font-semibold text-slate-900">{{ $workflow->name }}</h3><span class="px-2 py-1 rounded-md text-[10px] font-bold {{ $workflow->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500' }}">{{ $workflow->is_active ? 'Aktif' : 'Tidak Aktif' }}</span></div><p class="mt-1 text-xs text-slate-500">{{ \App\Support\HumanLabel::label($workflow->module) }} · {{ \App\Support\HumanLabel::label($workflow->transaction_type) }} · {{ $workflow->company_id ? 'Scope perusahaan' : 'Global' }}{{ $workflow->site_id ? ' · Site tertentu' : '' }}</p></div><form method="POST" action="{{ route('setting.approval-workflow.toggle', $workflow) }}">@csrf @method('PATCH')<button class="text-xs font-semibold text-slate-500 hover:text-amber-700">{{ $workflow->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form></div><div class="mt-4 grid md:grid-cols-3 gap-2">@foreach($workflow->steps->sortBy('sequence') as $step)<div class="rounded-lg border border-slate-200 bg-slate-50 p-3"><div class="text-[10px] font-bold text-slate-400">LEVEL {{ $step->sequence }}</div><div class="mt-1 text-xs font-semibold text-slate-700">{{ $step->name }}</div><div class="mt-1 text-[11px] text-slate-500">{{ $step->min_amount > 0 ? 'Mulai Rp '.number_format($step->min_amount,0,',','.') : 'Semua nominal' }}{{ $step->max_amount ? ' — Rp '.number_format($step->max_amount,0,',','.') : ' ke atas' }}</div></div>@endforeach</div></article>@empty<div class="p-10 text-center text-sm text-slate-400">Belum ada workflow.</div>@endforelse</div></section>
        <section x-show="open" x-cloak class="dashboard-card p-5"><h2 class="font-semibold text-slate-900">Workflow baru</h2><p class="text-xs text-slate-500 mt-1 mb-5">Semua threshold disimpan ke engine approval yang sudah digunakan transaksi.</p><form method="POST" action="{{ route('setting.approval-workflow.store') }}" class="space-y-3">@csrf<input name="code" required placeholder="Kode internal, mis. PO-APPROVAL" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm"><input name="name" required placeholder="Nama workflow" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm"><div class="grid grid-cols-2 gap-2"><input name="module" required placeholder="Modul" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm"><input name="transaction_type" required placeholder="Jenis dokumen" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm"></div><select name="company_id" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm"><option value="">Semua perusahaan</option>@foreach($companies as $company)<option value="{{ $company->id }}">{{ $company->name }}</option>@endforeach</select><select name="site_id" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm"><option value="">Semua site</option>@foreach($sites as $site)<option value="{{ $site->id }}">{{ $site->name }}</option>@endforeach</select><div class="border-t border-slate-100 pt-3"><div class="text-xs font-semibold text-slate-700 mb-2">Level 1</div><input name="steps[0][name]" required placeholder="Nama persetujuan" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm mb-2"><select name="steps[0][role_id]" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm mb-2"><option value="">Pilih peran approver</option>@foreach($roles as $role)<option value="{{ $role->id }}">{{ $role->name }}</option>@endforeach</select><div class="grid grid-cols-2 gap-2"><input name="steps[0][min_amount]" type="number" min="0" value="0" placeholder="Nominal mulai" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm"><input name="steps[0][max_amount]" type="number" min="0" placeholder="Nominal sampai" class="w-full h-10 px-3 rounded-lg border border-slate-200 text-sm"></div></div><button class="w-full h-10 rounded-lg bg-slate-900 text-white text-sm font-semibold">Simpan Workflow</button></form></section>
    </div>
</div>
@endsection
